"use client";
import {useState} from 'react';
import {commercialApi,type CommercialContext,type CommercialOrganization} from '@/lib/commercial';
import {parseDocument} from '@/lib/identity';
import {supabase} from '@/lib/supabase-browser';
import {useMutation} from './workflow-ui';
export function DocumentField({required=true}:{required?:boolean}){const [document,setDocument]=useState('');const parsed=parseDocument(document);return <label>CPF ou CNPJ<input className="input" name="document_number" autoComplete="off" required={required} maxLength={20} value={document} onChange={e=>setDocument(e.target.value)}/><small className="subtle">CNPJ, inclusive MEI, é recomendado para responsáveis. CPF é permitido. Identificação privada.</small>{document&&<small role="status">{parsed?`${parsed.type.toUpperCase()}: formato e dígitos válidos; identificação não verificada.`:'Confira o formato e os dígitos do CPF ou CNPJ.'}</small>}</label>}
export function BusinessSetup({context,organization,refresh}:{context:CommercialContext|null;organization?:CommercialOrganization;refresh:()=>Promise<void>}){
 const [role,setRole]=useState(organization?.market_role==='buyer'?'buyer':'provider');const mutation=useMutation(refresh);
 return <section className="panel" id="business-setup"><h2>Identificação e atividade comercial</h2><p className="subtle">{context?.identity_complete?`Identificação privada ${context.document_type?.toUpperCase()} · final ${context.document_last4}.`:'Complete sua identificação para novas operações comerciais. Seu histórico continua disponível.'} Escolha explicitamente quem contrata empresas e quem fornece equipes. Eventos antigos permanecem sem classificação até uma decisão autorizada.</p>{(!organization||organization.is_owner)&&<form className="form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const doc=String(f.get('document_number'));await mutation.run(async()=>{if(!parseDocument(doc))throw Error('Confira o CPF ou CNPJ.');await commercialApi(supabase).configureBusiness({...(organization?{organization_id:organization.id}:{}),display_name:String(f.get('name')),organization_type:String(f.get('type')) as 'team'|'company'|'agency',market_role:role as 'buyer'|'provider',buyer_subtype:role==='buyer'?String(f.get('subtype')) as 'agency'|'scenography':null,document:doc})},'Atividade comercial configurada.')}}><fieldset className="eventCreationFields" disabled={mutation.busy}><label>Nome da organização<input className="input" name="name" defaultValue={organization?.display_name} required minLength={2} maxLength={150}/></label><label>Tipo<select name="type" className="select" defaultValue="company"><option value="company">Empresa</option><option value="team">Equipe</option><option value="agency">Agência</option></select></label><label>Atividade<select className="select" value={role} disabled={!!organization&&organization.market_role!=='unclassified'} onChange={e=>setRole(e.target.value)}><option value="provider">Fornecedor de equipes e serviços</option><option value="buyer">Contratante de empresas</option></select></label>{role==='buyer'&&<label>Contratante<select className="select" name="subtype" defaultValue={organization?.buyer_subtype||'agency'}><option value="agency">Agência</option><option value="scenography">Cenografia</option></select></label>}<DocumentField/>{mutation.feedback}<button className="btn">Salvar atividade comercial</button></fieldset></form>}{organization?.is_owner&&<form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutation.run(()=>commercialApi(supabase).setFinanceMember(organization.id,String(f.get('profile')),f.get('enabled')==='on'),'Autorização financeira atualizada.')}}><h3>Autorizar financeiro de membro</h3><p className="subtle">Informe o ID de um membro ativo da sua organização. Coordenadores precisam desta autorização explícita.</p><label>ID do perfil membro<input className="input" name="profile" pattern="[0-9a-fA-F-]{36}" required/></label><label className="check"><input name="enabled" type="checkbox"/>Autorizar acesso financeiro</label><button className="btn secondary" disabled={mutation.busy}>Atualizar autorização</button></form>}</section>;
}
