"use client";
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase-browser';
import {pushSupport,safeNotificationLink,type NotificationCenter,type NotificationPreferences} from '@/lib/notifications';
async function request(path:string,options:RequestInit={}){
 const session=await supabase.auth.getSession();if(!session.data.session)throw new Error('Entre novamente para ver notificações.');
 const response=await fetch('/api/notifications'+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.data.session.access_token}`,...options.headers}});
 const result=await response.json();if(!response.ok)throw new Error(result.error==='confirmed_email_required'?'Confirme seu e-mail antes de ativar este canal.':result.error||'Não foi possível carregar notificações.');return result;
}
export function Notifications({specialties,onClose}:{specialties:{id:string;name:string}[];onClose:()=>void}){
 const [center,setCenter]=useState<NotificationCenter|null>(null),[preferences,setPreferences]=useState<NotificationPreferences|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[support,setSupport]=useState('unsupported'),[regionText,setRegionText]=useState('');
 async function refresh(){const data=await request('');setCenter(data);setPreferences(data.preferences);setRegionText(data.preferences.regions.join(', '))}
 useEffect(()=>{let active=true;request('').then(data=>{if(active){setCenter(data);setPreferences(data.preferences);setRegionText(data.preferences.regions.join(', '))}}).catch(e=>{if(active)setError(e.message)});setSupport(pushSupport({serviceWorker:'serviceWorker' in navigator,pushManager:'PushManager' in window,notification:'Notification' in window,permission:'Notification' in window?Notification.permission:'default'}));return()=>{active=false}},[]);
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await action()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function enablePush(){
  if(support!=='available'){setNotice('Push indisponível neste navegador. Sua central e e-mail continuam disponíveis.');return}
  // Called only by the button gesture, before any asynchronous server work.
  const permission=await Notification.requestPermission();if(permission!=='granted'){setSupport(permission==='denied'?'denied':'available');setNotice('Permissão não concedida. Sua central e e-mail continuam disponíveis.');return}
  const config=await request('/devices');if(!config.enabled){setNotice('Push aguardando configuração do servidor. Sua central e e-mail continuam disponíveis.');return}
  const registration=await navigator.serviceWorker.ready;
  const raw=atob(config.public_key.replace(/-/g,'+').replace(/_/g,'/'));const key=Uint8Array.from(raw,(c:string)=>c.charCodeAt(0));
  const existing=await registration.pushManager.getSubscription();const subscription=existing||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});
  try{await request('/devices',{method:'POST',body:JSON.stringify(subscription.toJSON())})}catch(error){if(!existing)await subscription.unsubscribe();throw error}
  if(preferences)await request('/preferences',{method:'PUT',body:JSON.stringify({...preferences,push_enabled:true})});await refresh();setNotice('Este dispositivo foi registrado. A entrega depende do navegador e da configuração do servidor.');
 }
 async function removeDevice(id:string){const device=center?.devices.find(d=>d.id===id);await request('/devices?id='+id,{method:'DELETE'});if('serviceWorker' in navigator){const registration=await navigator.serviceWorker.getRegistration();const subscription=await registration?.pushManager.getSubscription();if(subscription?.endpoint===device?.endpoint)await subscription?.unsubscribe()}await refresh();setNotice('Dispositivo removido da sua conta.')}
 return <section className="panel" aria-label="Central de notificações"><div className="sectionHead"><h2>Notificações e preferências</h2><button className="btn secondary" onClick={onClose}>Fechar notificações</button></div>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}{!center&&!error&&<p role="status">Carregando notificações…</p>}
 {center&&preferences&&<><p className="subtle">Todas as oportunidades abertas continuam disponíveis para navegar. As preferências controlam somente os alertas.</p><form className="form" onSubmit={e=>{e.preventDefault();void run(async()=>{await request('/preferences',{method:'PUT',body:JSON.stringify({...preferences,regions:regionText.split(',').map(r=>r.trim()).filter(Boolean)})});await refresh();setNotice('Preferências salvas.')})}}><fieldset className="eventCreationFields" disabled={busy}><label>Oportunidades para alertas<select className="select" value={preferences.mode} onChange={e=>setPreferences({...preferences,mode:e.target.value as NotificationPreferences['mode']})}><option value="relevant">Funções, região e datas escolhidas</option><option value="all_eligible">Todas as oportunidades elegíveis</option></select></label>{preferences.mode==='relevant'&&<><fieldset className="functionDraft"><legend>Funções (sem seleção: suas especialidades elegíveis)</legend>{specialties.map(s=><label className="check" key={s.id}><input type="checkbox" checked={preferences.specialty_ids.includes(s.id)} onChange={e=>setPreferences({...preferences,specialty_ids:e.target.checked?[...preferences.specialty_ids,s.id]:preferences.specialty_ids.filter(id=>id!==s.id)})}/>{s.name}</label>)}</fieldset><label>Regiões públicas (separe por vírgula)<input className="input" value={regionText} onChange={e=>setRegionText(e.target.value)}/></label><label>Desde<input className="input" type="date" value={preferences.date_from||''} onChange={e=>setPreferences({...preferences,date_from:e.target.value||null})}/></label><label>Até<input className="input" type="date" min={preferences.date_from||undefined} value={preferences.date_to||''} onChange={e=>setPreferences({...preferences,date_to:e.target.value||null})}/></label></>}
 <label>Frequência<select className="select" value={preferences.cadence} onChange={e=>setPreferences({...preferences,cadence:e.target.value as NotificationPreferences['cadence']})}><option value="immediate">Imediato (com limite por hora)</option><option value="daily">Resumo diário</option></select></label><label className="check"><input type="checkbox" checked={preferences.email_enabled} disabled={!center.email_confirmed} onChange={e=>setPreferences({...preferences,email_enabled:e.target.checked})}/>E-mail confirmado{!center.email_confirmed?' (confirme seu endereço)':''}</label><label className="check"><input type="checkbox" checked={preferences.push_enabled} onChange={e=>setPreferences({...preferences,push_enabled:e.target.checked})}/>Alertas nos dispositivos registrados</label><label className="check"><input type="checkbox" checked={!!preferences.paused_until&&new Date(preferences.paused_until)>new Date()} onChange={e=>setPreferences({...preferences,paused_until:e.target.checked?'9999-01-01T00:00:00Z':null})}/>Pausar e-mail e push até reativar</label><button className="btn">Salvar preferências de alertas</button></fieldset></form>
 {center.delivery&&!center.delivery.email.enabled&&<p className="notice">E-mail aguardando configuração do provedor e remetente verificado. Os alertas não são marcados como enviados.</p>}{center.delivery&&!center.delivery.push.enabled&&<p className="notice">Push aguardando configuração do servidor. A central continua disponível.</p>}<h3>Este dispositivo</h3><p className="subtle">No iPhone/iPad com iOS/iPadOS 16.4 ou superior, adicione o EventCore à Tela de Início, abra pelo ícone e toque no botão abaixo. Em Android e outros navegadores, o suporte depende do navegador e da permissão. A instalação não ativa alertas automaticamente.</p><button className="btn secondary" disabled={busy||support!=='available'} onClick={()=>void run(enablePush)}>Ativar push neste dispositivo</button>{support!=='available'&&<p>{support==='denied'?'Push bloqueado nas permissões do navegador.':'Este navegador não oferece push.'} A central e o e-mail continuam disponíveis.</p>}{center.devices.filter(d=>d.active).map(d=><p key={d.id}>Dispositivo registrado em {new Date(d.created_at).toLocaleDateString('pt-BR')} <button className="btn ghost" disabled={busy} onClick={()=>void run(()=>removeDevice(d.id))}>Remover dispositivo</button></p>)}
 <h3>Suas atualizações</h3>{center.notifications.map(n=><article className="operationRow" key={n.id}><div><strong>{n.title}</strong><span>{new Date(n.created_at).toLocaleString('pt-BR')}{n.read_at?' · Lida':''}</span></div>{safeNotificationLink(n.link)&&<a className="btn secondary" href={n.link} onClick={()=>void request('',{method:'PATCH',body:JSON.stringify({id:n.id})}).catch(()=>{})}>Abrir atualização</a>}</article>)}{!center.notifications.length&&<p className="empty">Nenhuma atualização disponível.</p>}</>}
 </section>;
}
export function OpportunityShare({id}:{id:string}){const url=`https://eventcore.space/o/${id}`;return <div className="actions"><a className="btn ghost" href={`/o/${id}`} target="_blank" rel="noopener noreferrer">Prévia pública</a><a className="btn ghost" href={`https://wa.me/?text=${encodeURIComponent('Oportunidade no EventCore: '+url)}`} target="_blank" rel="noopener noreferrer">Compartilhar no WhatsApp</a></div>}
