"use client";
import {useEffect,useState} from 'react';
import {workflowApi,type ProviderPeople,type CommercialOrganization} from '@/lib/commercial';
import {supabase} from '@/lib/supabase-browser';
import {useMutation} from './workflow-ui';
export function ProviderPeoplePanel({organization,directory}:{organization:CommercialOrganization;directory:{freelancer_id:string;full_name:string}[]}){
 const [people,setPeople]=useState<ProviderPeople>({base:[],teams:[]}),[error,setError]=useState(''),[loading,setLoading]=useState(true);const api=workflowApi(supabase);
 async function refresh(){const result=await api.people(organization.id);setPeople(result)}
 useEffect(()=>{let active=true;setLoading(true);setError('');api.people(organization.id).then(p=>{if(active)setPeople(p)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[organization.id]);const m=useMutation(refresh);
 return <section className="panel"><h2>Base e equipes habituais</h2><p className="subtle">A base e as equipes são listas reutilizáveis. A equipe real de cada trabalho depende de convite e aceite; inclusão aqui não confirma disponibilidade.</p>{loading&&<p role="status">Carregando base…</p>}{error&&<p role="alert" className="error">{error}</p>}{m.feedback}<h3>Base de profissionais</h3>{people.base.length?people.base.map(p=><div key={p.freelancer_id} className="operationRow"><strong>{p.full_name}</strong>{organization.is_owner&&<button className="btn ghost" disabled={m.busy} onClick={()=>m.run(()=>api.setBaseMember(organization.id,p.freelancer_id,!p.active))}>{p.active?'Retirar da base':'Reativar'}</button>}</div>):<p className="empty">Sua base está vazia.</p>}{organization.is_owner&&<form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void m.run(()=>api.setBaseMember(organization.id,String(f.get('worker')),true))}}><label>Adicionar profissional<select className="select" name="worker" required><option value="">Selecione</option>{directory.map(p=><option key={p.freelancer_id} value={p.freelancer_id}>{p.full_name}</option>)}</select></label><button className="btn" disabled={m.busy}>Adicionar à base</button></form>}<h3>Equipes habituais</h3>{people.teams.map(t=><div className="functionDraft" key={t.id}><strong>{t.name}</strong><p>{t.freelancer_ids.map(id=>people.base.find(p=>p.freelancer_id===id)?.full_name||directory.find(p=>p.freelancer_id===id)?.full_name||'Profissional').join(', ')||'Nenhum membro'}</p>{organization.is_owner&&<><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void m.run(()=>api.saveTeam(organization.id,t.id,String(f.get('name'))))}}><label>Nome da equipe<input className="input" name="name" defaultValue={t.name} required/></label><button className="btn secondary" disabled={m.busy}>Renomear equipe</button></form>{people.base.filter(p=>p.active).map(p=><label className="check" key={p.freelancer_id}><input type="checkbox" disabled={m.busy} checked={t.freelancer_ids.includes(p.freelancer_id)} onChange={e=>m.run(()=>api.setTeamMember(t.id,p.freelancer_id,e.target.checked))}/>{p.full_name}</label>)}<button className="btn ghost" disabled={m.busy} onClick={()=>m.run(()=>api.deleteTeam(t.id))}>Excluir lista habitual</button></>}</div>)}{!people.teams.length&&<p className="empty">Nenhuma equipe habitual.</p>}{organization.is_owner&&<form className="form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await m.run(()=>api.saveTeam(organization.id,null,String(f.get('name')))))form.reset()}}><label>Nome da nova equipe habitual<input className="input" name="name" required maxLength={150}/></label><button className="btn" disabled={m.busy}>Criar equipe habitual</button></form>}</section>;
}
