"use client";
import {useEffect,useState} from 'react';
import {workflowApi,type CommercialOrganization,type WorkerHistory,type ProviderHistory} from '@/lib/commercial';
import {supabase} from '@/lib/supabase-browser';
export function RelationshipHistory({organization}:{organization:CommercialOrganization}){
 const [rows,setRows]=useState<(WorkerHistory|ProviderHistory)[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError('');setRows([]);const api=workflowApi(supabase);(organization.market_role==='buyer'?api.providerHistory(organization.id):api.workerHistory(organization.id)).then(r=>{if(active)setRows(r)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[organization.id,organization.market_role,attempt]);
 return <section className="panel"><div className="sectionHead"><h2>Histórico de relações de trabalho</h2><button className="btn secondary" disabled={loading} onClick={()=>setAttempt(n=>n+1)}>Atualizar histórico</button></div><p className="subtle">Somente trabalhos efetivamente concluídos e confirmados. {organization.market_role==='buyer'?'Ordem: estrelas, avaliações, trabalhos, nome e ID.':'Ordem: pontualidade registrada, estrelas, trabalhos, nome e ID. Valores sem evidência ficam por último.'}</p>{loading?<p role="status">Carregando histórico…</p>:error?<p className="error" role="alert">{error}</p>:rows.length?rows.map(row=><article className="operationRow" key={'freelancer_id'in row?row.freelancer_id:row.organization_id}><div><strong>{'full_name'in row?row.full_name:row.display_name}</strong><span>{row.job_count} trabalhos · {row.review_count} avaliações · {row.average_stars==null?'Sem avaliações':`★ ${Number(row.average_stars).toFixed(1)}/5`}</span>{'punctuality'in row&&<span>Pontualidade: {row.punctuality==null?'Sem registros':`${row.punctuality}%`} · {row.punctuality_count} registros</span>}</div></article>):<p className="empty">Nenhuma relação concluída confirmada.</p>}</section>;
}
