"use client";
import {workflowApi,type AssignmentTerms,type WorkerWorkAssignment} from '@/lib/commercial';
import {acceptedAmount,mutableWork} from '@/lib/work-presentation';
import {supabase} from '@/lib/supabase-browser';
import {money,workDate,useMutation} from './workflow-ui';
export function WorkerWork({rows,refresh}:{rows:WorkerWorkAssignment[];refresh:()=>Promise<void>}){const api=workflowApi(supabase),m=useMutation(refresh);async function attendance(id:string,kind:'in'|'out'){const pos=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{timeout:12000,enableHighAccuracy:true}));await api.recordAttendance(id,kind,pos.coords.latitude,pos.coords.longitude)}
 return <section className="panel"><h2>Minha escala, condições e recebimentos</h2>{m.feedback}{!rows.length&&<p className="empty">Você ainda não tem convocações.</p>}{rows.map(a=>{const terms=a.accepted_terms||a.offered_terms,open=mutableWork(a.event_status,a.end_at);return <article className="functionDraft" id={"assignment-"+a.id} tabIndex={-1} key={a.id}><h3>{a.event_name} · {a.function_name}</h3><p>{workDate(a.start_at)} · {a.venue} · {a.status}</p><p>Valor aceito a pagar: {money(acceptedAmount(a))}</p>{terms&&<TermsSummary terms={terms}/>}{a.offered_terms&&a.offered_terms.id!==a.accepted_terms?.id&&<div className="notice"><p>Oferta revisão {a.offered_terms.revision}: {money(a.offered_terms.total)}. O valor só muda após seu aceite.</p><TermsSummary terms={a.offered_terms}/><button className="btn" disabled={m.busy||!open} onClick={()=>m.run(()=>api.acceptTerms(a.offered_terms!.id),'Condições aceitas.')}>Aceitar condições revisão {a.offered_terms.revision}</button></div>}<div className="actions">{['invited','reserve'].includes(a.status)&&open&&<><button className="btn" disabled={m.busy} onClick={()=>m.run(()=>api.respond(a.id,'confirmed'),'Convocação confirmada.')}>Confirmar convocação</button><button className="btn secondary" disabled={m.busy} onClick={()=>m.run(()=>api.respond(a.id,'cancelled'),'Convocação recusada.')}>Não posso ir</button></>}{a.status==='confirmed'&&<button className="btn" disabled={m.busy} onClick={()=>m.run(()=>attendance(a.id,'in'),'Check-in registrado.')}>Fazer check-in</button>}{a.status==='checked_in'&&<button className="btn" disabled={m.busy} onClick={()=>m.run(()=>attendance(a.id,'out'),'Check-out registrado.')}>Fazer check-out</button>}{a.event_status==='completed'&&!a.completion_confirmed&&<button className="btn secondary" disabled={m.busy} onClick={()=>m.run(()=>api.confirmWorkerCompletion(a.id),'Trabalho concluído confirmado.')}>Confirmar trabalho concluído</button>}</div><h4>Pagamentos registrados</h4>{a.payments.map(p=><p key={p.id}>{money(p.amount)} · {p.status} · {p.method||'Método não informado'}{p.paid_at?` · ${workDate(p.paid_at)}`:''}</p>)}{!a.payments.length&&<p className="subtle">Nenhum pagamento registrado.</p>}<details><summary>Histórico imutável de condições</summary>{a.terms_history.map(t=><p key={t.id}>Revisão {t.revision} · {money(t.total)} · {t.accepted_at?'Aceita':'Oferta'}</p>)}{!a.terms_history.length&&<p>Total histórico: {money(a.legacy_agreed_amount)}. Sem multiplicação por dias.</p>}</details></article>})}</section>;
}

function TermsSummary({terms}:{terms:AssignmentTerms}){return <p>{terms.contract_days==null?'Dias não informados':`${terms.contract_days} dias`} · {terms.planned_hours==null?'Horas não informadas':`${terms.planned_hours} horas`} · {terms.basis==='daily'?'Diária':'Por serviço'}: {money(terms.rate)} · Acréscimos {money(terms.additions)} · Descontos {money(terms.deductions)} · {terms.benefits||'Benefícios não informados'}</p>}
