import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const output=process.env.EVENTCORE_BROWSER_OUTPUT||'/workspace/scratch/0d27d86074e8/eventcore-task3-evidence';
await fs.mkdir(output,{recursive:true});
const port=10000+Math.floor(Math.random()*50000),base='http://127.0.0.1:'+port;
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(port)],{cwd:process.cwd(),env:{...process.env,NEXT_PUBLIC_SUPABASE_URL:'http://127.0.0.1:18765',NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:'preview-publishable-key'},stdio:['ignore','ignore','pipe']});
server.stderr.on('data',c=>process.stderr.write(c));process.on('exit',()=>server.kill());
let browser;
const id=n=>`${String(n).padStart(8,'0')}-1111-4111-8111-111111111111`,profileId=id(1),providerId=id(2),buyerId=id(3),eventId=id(4),serviceId=id(5),workerId=id(6),assignmentId=id(7),clientId=id(8),quoteId=id(9),contractId=id(10),requestId=id(11),teamId=id(12);
const specialty={id:id(13),slug:'loader',name:'Carregador',active:true,sort_order:1};
const today=new Date().toISOString().slice(0,10);
const results=[];
try{
 for(let n=0;n<60;n++){try{await new Promise((resolve,reject)=>{const r=http.get(base,res=>{res.resume();res.statusCode===200?resolve():reject(Error(String(res.statusCode)))});r.on('error',reject)});break}catch(e){if(n===59)throw e;await new Promise(r=>setTimeout(r,200))}}
 browser=await chromium.launch({executablePath:'/workspace/scratch/0d27d86074e8/eventcore-browser-runtime/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
 for(const role of (process.env.EVENTCORE_CHECK_ROLE?[process.env.EVENTCORE_CHECK_ROLE]:['buyer','provider','worker','coordinator','legacy','finance']))for(const width of (process.env.EVENTCORE_CHECK_WIDTH?[+process.env.EVENTCORE_CHECK_WIDTH]:[360,390,1280])){
  const context=await browser.newContext({viewport:{width,height:844},locale:'pt-BR',timezoneId:'America/Sao_Paulo',serviceWorkers:'block',permissions:['geolocation'],geolocation:{latitude:-22.9,longitude:-43.2}});
  const profile={id:profileId,full_name:'Responsável '+role,role:role==='legacy'?'admin':role==='coordinator'?'coordinator':'freelancer',active:true,profile_type:role==='legacy'?null:role==='worker'?'freelancer':role==='buyer'?'agency':'company',onboarding_completed:true,professional_status:'available',bio:'Apresentação real'};
  const org={id:role==='buyer'?buyerId:providerId,display_name:role==='buyer'?'Agência Aurora':'Equipe Aurora',organization_type:role==='buyer'?'agency':'company',market_role:role==='buyer'?'buyer':'provider',buyer_subtype:role==='buyer'?'agency':null,is_owner:!['coordinator','finance'].includes(role),can_operate:role!=='finance',can_finance:role!=='coordinator'};
  const commercial={profile_id:profileId,identity_complete:role!=='legacy',document_type:role==='legacy'?null:'cpf',document_last4:role==='legacy'?null:'4725',organizations:['legacy','worker'].includes(role)?[]:[org]};
  let event={id:eventId,client_id:clientId,name:'Trabalho privado Aurora',venue:'Endereço exato privado',start_at:'2099-10-07T11:00:00Z',end_at:'2099-10-07T22:00:00Z',status:'confirmed',arrival_tolerance_minutes:15,calendar_sync_status:'synced',organization_id:role==='legacy'?null:providerId,created_by_profile_id:profileId};
  let services=[{id:serviceId,event_id:eventId,label:'Carregador',service_type:'loader',specialty_id:specialty.id,quantity_needed:10,reserve_target:1,contract_days:role==='legacy'?null:2,planned_hours:8,briefing:'Orientação privada',requirements:'Requisito privado',visibility:'private',application_enabled:false}];
  const term=(n,total)=>({id:id(20+n),assignment_id:assignmentId,revision:n,basis:'daily',rate:total/2,contract_days:2,planned_hours:8,benefits:'Alimentação',additions:0,deductions:0,total,created_at:today+'T12:00:00Z',accepted_at:n===1?today+'T12:01:00Z':null});
  let worker={id:assignmentId,freelancer_id:workerId,event_service_id:serviceId,event_id:eventId,event_name:event.name,venue:event.venue,start_at:event.start_at,end_at:event.end_at,event_status:event.status,status:'invited',function_name:'Carregador',legacy_agreed_amount:440,offered_terms:term(2,460),accepted_terms:term(1,440),terms_history:[term(1,440),term(2,460)],payments:[],completion_confirmed:false};
  const workerHistory=[{...worker,id:id(80),event_id:id(81),event_name:'Trabalho concluído real',start_at:'2026-10-01T11:00:00Z',end_at:'2026-10-01T22:00:00Z',event_status:'completed',status:'checked_out',offered_terms:worker.accepted_terms,terms_history:[worker.accepted_terms],completion_confirmed:true,payments:[{id:id(82),amount:440,status:'paid',method:'pix',paid_at:today,term_id:worker.accepted_terms.id}]},{...worker,id:id(83),event_id:id(84),event_name:'Convite cancelado',status:'cancelled',offered_terms:worker.accepted_terms,terms_history:[worker.accepted_terms]}];
  let assignments=[{id:assignmentId,event_service_id:serviceId,freelancer_id:workerId,status:'invited'}];
  let people={base:[{freelancer_id:workerId,full_name:'Rafael Almeida',city:'Rio',active:true}],teams:[{id:teamId,name:'Equipe habitual montagem',freelancer_ids:[workerId]}]};
  let quote={id:quoteId,revision:1,status:role==='buyer'?'sent':'draft',title:'Orçamento Aurora',issued_at:today,event_date:'2099-10-07',venue:'Local contratado Aurora',valid_until:'2099-10-07',payment_terms:'Pix na entrega',show_unit_prices:true,client_total:5600,issuer:{id:providerId,display_name:'Equipe Aurora'},client:{display_name:'Agência Aurora'},request_id:requestId,contract_id:null,items:[{id:id(30),label:'Equipe montagem',quantity:10,contract_days:2,planned_hours:8,client_unit_price:280,line_total:5600}]};
  let workspace={requests:[{id:requestId,provider_organization_id:providerId,buyer_organization_id:buyerId,title:'Montagem Aurora',description:'Equipe para dois dias',event_date:null,venue:null,status:'quoted',created_by:profileId,created_at:today}],quotes:[quote],contracts:role==='buyer'?[]:[{id:contractId,proposal_id:quoteId,request_id:requestId,client_id:clientId,accepted_by:profileId,provider_organization_id:providerId,buyer_organization_id:buyerId,sale_total:5600,quote_snapshot:quote,accepted_at:today,acceptance_method:'platform',received_total:0,receivable_total:5600}],receipts:[]};
  let finance={event_id:eventId,sale_source:role==='legacy'?'legacy_contracted_gross':'accepted_contract',sale_contracted:5600,sale_received:role==='legacy'?null:0,sale_receivable:role==='legacy'?null:5600,sale_deductions:0,labor_contracted:440,labor_paid:0,labor_payable:440,unknown_labor_count:0,other_contracted:0,other_paid:0,other_payable:0,unknown_expense_count:0,estimated_result:5160,result_label:'estimated_before_unresolved_expenses_and_taxes',expenses:[]};
  const calls=[],errors=[];let failSave=true;let completedConfirmed=false;
  const user={id:profileId,aud:'authenticated',role:'authenticated',email:'fixture@example.invalid',app_metadata:{provider:'email'},user_metadata:{},created_at:today};const expires=Math.floor(Date.now()/1000)+3600,token=[Buffer.from('{"alg":"HS256","typ":"JWT"}').toString('base64url'),Buffer.from(JSON.stringify({sub:profileId,role:'authenticated',aud:'authenticated',exp:expires})).toString('base64url'),'fixture'].join('.');
  await context.addInitScript(({token,user,expires})=>localStorage.setItem('sb-127-auth-token',JSON.stringify({access_token:token,refresh_token:'fixture',expires_in:3600,expires_at:expires,token_type:'bearer',user})),{token,user,expires});
  const image='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80"><rect width="80" height="80" fill="green"/></svg>');
  await context.route('**/api/profile/photos**',r=>r.fulfill({json:{avatar:null,portfolio:[{id:id(31),kind:'portfolio',url:image,caption:'Trabalho real',created_at:today}]}}));
  await context.route('**/api/specialties',r=>r.fulfill({json:[specialty]}));
  await context.route(url=>url.hostname==='127.0.0.1'&&url.port==='18765',async route=>{
   const req=route.request(),url=new URL(req.url()),name=url.pathname.split('/').at(-1),args=req.method()==='POST'?req.postDataJSON():null;
   const headers={'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'};
   if(req.method()==='OPTIONS')return route.fulfill({status:204,headers});
   calls.push({name,args,method:req.method()});let data;
   if(url.pathname.includes('/auth/'))data=user;
   else if(url.pathname.includes('/rpc/')){
    assert.equal(req.headers().authorization,`Bearer ${token}`,'Product RPC lost caller session');
    switch(name){
     case 'get_commercial_context':data=commercial;break;
     case 'get_event_operations':assert.notEqual(role,'finance','Finance permission must not call operations');data={event,services,assignments,can_finance:role!=='coordinator',can_hire:role!=='coordinator'&&commercial.identity_complete};break;
     case 'get_work_finance_index':data=['worker','buyer','coordinator'].includes(role)?[]:[{event_id:eventId,event_name:event.name,organization_id:event.organization_id}];break;
     case 'get_work_finance':assert.notEqual(role,'coordinator');data=finance;break;
     case 'get_event_remunerations':assert.notEqual(role,'coordinator');data=[worker];break;
     case 'get_my_work_assignments':data=[worker,...(role==='worker'?workerHistory:[])];break;
     case 'get_my_schedule':data={events:[event],services};break;
     case 'get_professional_directory':data=[{freelancer_id:workerId,full_name:'Rafael Almeida',city:'Rio',rating:null,review_count:0,completed_jobs:0,specialties:['Carregador']}];break;
     case 'get_work_opportunities':data=[{service_id:serviceId,event_id:eventId,event_name:'Oportunidade: Carregador',start_at:'2026-10-07T00:00:00Z',end_at:null,venue:'Barra',function_name:'Carregador',specialty_id:specialty.id,vacancies:10,amount:role==='worker'?440:null,contractor_name:'Equipe Aurora',requirements:'Descrição pública',event_status:'confirmed',compatible:true,contract_days:2,remuneration:null}];break;
     case 'get_organization_roster':data=[];break;
     case 'get_commercial_workspace':assert.notEqual(role,'coordinator');data=workspace;break;
     case 'list_commercial_providers':data=[{id:providerId,display_name:'Equipe Aurora',organization_type:'company',specialties:['Carregador']}];break;
     case 'get_provider_presentation':data={id:providerId,display_name:'Equipe Aurora',organization_type:'company',bio:'Portfólio real',specialties:['Carregador'],average_stars:null,review_count:0,job_count:0};break;
     case 'create_contract_request':workspace.requests.push({id:id(40),provider_organization_id:providerId,buyer_organization_id:buyerId,title:args.p_title,description:args.p_description,status:'requested',created_at:today});data=id(40);break;
     case 'save_sale_quote':if(failSave){failSave=false;return route.fulfill({status:400,headers,json:{message:'fixture_save_failure',code:'P0001'}})}quote={...args.p_quote,issuer:quote.issuer,client:quote.client,issued_at:quote.issued_at,contract_id:null,event_date:args.p_quote.event_date||null,venue:args.p_quote.venue??null,id:quoteId,revision:quote.revision+1,status:'draft',items:args.p_items.map((i,n)=>({...i,planned_hours:i.planned_hours??null,id:id(50+n),line_total:i.quantity*i.contract_days*i.client_unit_price})),client_total:args.p_items.reduce((s,i)=>s+i.quantity*i.contract_days*i.client_unit_price,0)};workspace.quotes=[quote];data=quoteId;break;
     case 'get_sale_quote':data=quote;break;
     case 'submit_sale_quote':quote.status='sent';data=null;break;
     case 'accept_sale_quote':quote.status='accepted';workspace.contracts=[{id:contractId,proposal_id:quoteId,request_id:requestId,client_id:clientId,accepted_by:profileId,provider_organization_id:providerId,buyer_organization_id:buyerId,sale_total:5600,quote_snapshot:quote,accepted_at:today,acceptance_method:'platform',received_total:0,receivable_total:5600}];data=contractId;break;
     case 'record_customer_receipt':workspace.receipts.push({id:id(52),contract_id:contractId,amount:args.p_amount,method:args.p_method,received_on:args.p_received_on});workspace.contracts[0].received_total+=args.p_amount;workspace.contracts[0].receivable_total-=args.p_amount;data=id(52);break;
     case 'get_buyer_work_status':data={contract_id:contractId,sale_total:5600,quote,received_total:0,work:{event_id:eventId,name:'Entrega Aurora',venue:'Local contratado',start_at:'2026-10-01T12:00:00Z',end_at:'2026-10-01T22:00:00Z',status:'completed',completion_confirmed:completedConfirmed}};break;
     case 'confirm_contract_completion':completedConfirmed=true;data=null;break;
     case 'submit_provider_rating':data=id(53);break;
     case 'get_provider_people':data=people;break;
     case 'get_provider_worker_history':data=[{freelancer_id:workerId,full_name:'Rafael Almeida',city:'Rio',job_count:1,average_stars:null,review_count:0,punctuality:null,punctuality_count:0}];break;
     case 'get_buyer_provider_history':data=[];break;
     case 'set_provider_base_member':data=null;break;
     case 'save_provider_team':people.teams.push({id:id(60),name:args.p_name,freelancer_ids:[]});data=id(60);break;
     case 'set_provider_team_member':data=null;break;
     case 'invite_selected_workers':assert.deepEqual(args.p_freelancer_ids,[workerId]);data=[assignmentId];break;
     case 'hire_application':data=assignmentId;break;
     case 'apply_for_opportunity':data=id(73);break;
     case 'publish_work_function':services[0].visibility=args.p_published?'open':'private';data=null;break;
     case 'propose_assignment_terms':assert.equal(args.p_terms.contract_days,2);assert.equal(args.p_terms.planned_hours,8);worker.offered_terms={...worker.offered_terms,revision:3,rate:args.p_terms.rate,total:args.p_terms.rate*2};data=id(23);break;
     case 'accept_assignment_terms':worker.accepted_terms={...worker.offered_terms,accepted_at:today};data=null;break;
     case 'respond_to_assignment':worker.status=args.p_status;assignments[0].status=args.p_status;data=null;break;
     case 'mark_assignment_paid':worker.payments=[{id:id(70),amount:440,status:'paid',method:args.p_method,paid_at:today,term_id:worker.accepted_terms.id}];data=null;break;
     case 'record_assignment_attendance':worker.status=args.p_kind==='in'?'checked_in':'checked_out';data=null;break;
     case 'configure_business_identity':assert.equal(args.p_payload.document,'529.982.247-25');assert.equal(args.p_payload.market_role,'provider');org.display_name=args.p_payload.display_name;commercial.identity_complete=true;commercial.document_type='cpf';commercial.document_last4='4725';commercial.organizations=[org];data=providerId;break;
     case 'set_organization_finance_member':assert.equal(args.p_profile_id,id(71));data=null;break;
     case 'create_external_work_client':data=clientId;break;
     case 'create_event_with_services':assert.equal(args.p_event.origin,'whatsapp');assert.equal(args.p_services[0].freelancer_unit_cost,440);assert.equal(args.p_services[0].contract_days,2);assert.equal(args.p_services[0].open_marketplace,false);event={...event,...args.p_event,name:args.p_event.name};services=[{...services[0],...args.p_services[0],label:'Carregador'}];data={event,services};break;
     case 'get_professional_reputation':data={name:'Rafael Almeida',availability:'available',bio:'Trabalhos realizados',reviews:[]};break;
     default:throw Error('Unexpected RPC '+name);
    }
   }else{
    const tables={profiles:[profile],specialties:[specialty],profile_specialties:[{specialty_id:specialty.id}],organizations:commercial.organizations.map(o=>({...o,owner_profile_id:role==='finance'?id(99):profileId,active:true,created_at:today})),events:role==='finance'?[]:[event],job_applications:['worker','finance'].includes(role)?[]:[{id:id(72),event_service_id:serviceId,freelancer_id:workerId,status:'interested',created_at:today}],ratings:[],clients:role==='finance'?[]:[{id:clientId,trade_name:'Cliente externo real',active:true,organization_id:providerId}],freelancers:[{id:workerId,profile_id:profileId,full_name:'Rafael Almeida',active:true,rating:0,completed_jobs:0}],integrations:[]};
    assert.ok(name in tables,'Unexpected broad raw table '+name);data=tables[name];if(req.headers().accept?.includes('application/vnd.pgrst.object+json'))data=data[0]||null;
   }
   return route.fulfill({status:200,headers,contentType:'application/json',body:JSON.stringify(data)});
  });
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base,{waitUntil:'networkidle'});await page.locator('.appHeader').waitFor();
  async function navigate(label){const nav=page.locator(width<851?'.mobileNav':'.sidebar nav'),button=nav.getByRole('button',{name:label,exact:true});if(await button.count())await button.click();else{await page.locator('.accountMenu summary').click();await page.locator('.accountDropdown').getByRole('button',{name:label,exact:true}).click()}await page.getByRole('heading',{name:label,level:1,exact:true}).waitFor()}
  async function geometry(){const g=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,header:getComputedStyle(document.querySelector('.appHeader')).backgroundColor,background:getComputedStyle(document.body).backgroundColor}));assert.ok(g.scroll<=g.width+1,`Overflow ${role}/${width}: ${JSON.stringify(g)}`);assert.equal(g.header,'rgb(255, 255, 255)');assert.equal(g.background,'rgb(245, 249, 247)');if(width<851){const box=await page.locator('.mobileNav').boundingBox();assert.ok(box&&box.y>=0&&box.y+box.height<=845,'Mobile navigation stays visible')}}
  async function capture(step){await page.screenshot({path:path.join(output,`${role}-${width}-${step}.png`),fullPage:true})}
  if(role==='coordinator'){await navigate('Início');await page.getByRole('button',{name:/^Abrir Trabalho privado Aurora/}).click();await page.locator('.operator h2').waitFor();assert.equal(await page.getByRole('button',{name:'Publicar vaga',exact:true}).count(),0,'Coordinator without finance cannot publish');await page.getByRole('button',{name:'Voltar para meus eventos'}).click();await navigate('Equipe');assert.equal(await page.getByRole('button',{name:'Adicionar à base',exact:true}).count(),0,'Only owner can change provider base');assert.equal(await page.getByRole('button',{name:'Criar equipe habitual',exact:true}).count(),0,'Only owner can change reusable teams')}const routes=await page.locator('.sidebar nav button').allTextContents();for(const label of routes){await navigate(label.trim());await geometry()}
  if(role!=='worker')assert.deepEqual(await page.locator('.mobileNav button').allTextContents(),['Início','Dashboard','Clientes','Equipe','Eventos']);
  if(role==='buyer'){
   await navigate('Clientes');const request=page.locator('form').filter({has:page.getByRole('heading',{name:'Solicitar orçamento'})});await request.locator('[name=provider]').selectOption(providerId);await request.locator('[name=title]').fill('Solicitação nova');await request.locator('[name=description]').fill('Montagem em dois dias');await request.getByRole('button',{name:'Enviar solicitação'}).click();await page.getByText('Solicitação enviada.',{exact:true}).waitFor();
   await page.getByRole('button',{name:'Ver perfil e portfólio'}).click();await page.getByText('Portfólio real',{exact:false}).waitFor();await page.locator('.professionalPhotos img').waitFor();await geometry();await page.getByRole('button',{name:'Fechar perfil'}).click();
   await page.getByRole('button',{name:'Aceitar orçamento'}).click();await page.getByText('Contrato aceito.',{exact:true}).waitFor();await page.getByRole('button',{name:'Acompanhar trabalho'}).click();await page.getByRole('button',{name:'Confirmar trabalho concluído'}).click();await page.getByRole('button',{name:'Avaliar fornecedor'}).click();await page.getByText('Avaliação registrada.',{exact:true}).waitFor();
   assert.equal(await page.getByText('Equipe contratada',{exact:true}).count(),0);assert.equal(calls.some(c=>c.name==='get_work_finance'),false);assert.equal(calls.some(c=>c.name==='create_event_with_services'),false);await capture('commercial');
  }
  if(role==='provider'){
   await navigate('Clientes');await page.getByRole('button',{name:'Editar rascunho'}).click();const editor=page.locator('form').filter({has:page.getByRole('heading',{name:'Editar rascunho',exact:true})});await editor.locator('[name=title]').fill('Orçamento editado');await editor.getByRole('button',{name:'Salvar rascunho'}).click();await page.getByText('fixture_save_failure',{exact:true}).waitFor();assert.equal(await editor.locator('[name=title]').inputValue(),'Orçamento editado');await editor.getByRole('button',{name:'Salvar rascunho'}).click();await page.getByText('Rascunho salvo.',{exact:true}).waitFor();assert.equal(quote.event_date,'2099-10-07','Title edit preserves event date');assert.equal(quote.venue,'Local contratado Aurora','Title edit preserves venue');assert.equal(quote.items[0].planned_hours,8,'Title edit preserves item hours');await page.getByRole('button',{name:'Enviar orçamento'}).click();await page.getByText('Orçamento enviado.',{exact:true}).waitFor();
   const receipt=page.locator('form').filter({has:page.getByRole('button',{name:'Registrar recebimento',exact:true})});await receipt.locator('[name=amount]').fill('1000');await receipt.getByRole('button',{name:'Registrar recebimento'}).click();await page.getByText('Recebimento registrado.',{exact:true}).waitFor();
   await navigate('Equipe');const team=page.locator('form').filter({has:page.getByRole('button',{name:'Criar equipe habitual'})});await team.locator('[name=name]').fill('Equipe extra');await team.getByRole('button',{name:'Criar equipe habitual'}).click();await page.getByText('Equipe extra',{exact:true}).waitFor();assert.ok((await page.locator('main').innerText()).includes('Pontualidade: Sem registros'));
   await navigate('Eventos');const form=page.locator('.eventCreationForm');await form.locator('[name=name]').fill('Novo trabalho externo');await form.locator('[name=client_id]').selectOption(clientId);await form.locator('[name=origin]').selectOption('whatsapp');await form.locator('[name=venue]').fill('Local privado novo');await form.locator('[name=start_at]').fill('2099-10-07T08:00');await form.locator('[name=end_at]').fill('2099-10-07T19:00');await form.getByRole('button',{name:'Adicionar função',exact:true}).click();await form.locator('[name$=".specialty_id"]').selectOption(specialty.id);await form.locator('[name$=".quantity_needed"]').fill('10');await form.locator('[name$=".contract_days"]').fill('2');await form.locator('[name$=".remuneration_rate"]').fill('220');await form.getByRole('button',{name:'Criar evento',exact:true}).click();await page.locator('.operator h2').waitFor();assert.equal(await page.locator('.eventsGrid').count(),0);assert.equal(await page.locator('input[name$=".contract_days"]').count(),0);const panes=await page.locator('.eventTabs button').all();assert.equal(panes.length,6);for(const pane of panes){await pane.click();await geometry()}
   await page.getByRole('button',{name:'Escala',exact:true}).click();await page.locator('.operator select[name=service]').selectOption(serviceId);await page.getByLabel('Selecionar equipe habitual').selectOption(teamId);await page.getByRole('button',{name:'Enviar convites específicos'}).click();await page.getByText('Convites enviados aos profissionais selecionados.',{exact:true}).waitFor();await page.getByRole('button',{name:'Ver perfil profissional',exact:true}).click();await page.locator('.reputationModal .professionalPhotos img').waitFor();await page.locator('.reputationModal').getByRole('button',{name:'Fechar',exact:true}).click();
   await page.getByRole('button',{name:'Candidaturas',exact:true}).click();await page.getByRole('button',{name:'Contratar',exact:true}).click();await page.getByText('Profissional convidado. O aceite é do trabalhador.',{exact:true}).waitFor();
   await page.getByRole('button',{name:'Pagamentos',exact:true}).click();await page.getByText('Propor revisão de remuneração',{exact:true}).click();await page.locator('[name=rate]').fill('230');await page.getByRole('button',{name:'Propor revisão',exact:true}).click();await page.getByText('Oferta de revisão enviada para aceite.',{exact:true}).waitFor();assert.match(await page.locator('.operator').innerText(),/Total aceito: R\$\s*440,00/);await page.getByRole('button',{name:'Registrar pagamento por Pix'}).click();await page.getByText('Pagamento registrado.',{exact:true}).waitFor();await geometry();const splitAmounts=await page.locator('.operator .metric strong').evaluateAll(items=>items.flatMap(item=>{const value=item.textContent||'',offset=value.search(/\d/);if(offset<0)return [];const range=document.createRange();range.setStart(item.firstChild,offset);range.setEnd(item.firstChild,value.length);return range.getClientRects().length>1?[value]:[]}));assert.deepEqual(splitAmounts,[],'BRL numeric values must stay on one line');await capture('work-finance');
   await page.getByRole('button',{name:'Voltar para meus eventos'}).click();await navigate('Meu perfil');const permission=page.locator('form').filter({has:page.getByRole('button',{name:'Atualizar autorização'})});await permission.locator('[name=profile]').fill(id(71));await permission.locator('[name=enabled]').check();await permission.getByRole('button',{name:'Atualizar autorização'}).click();await page.getByText('Autorização financeira atualizada.',{exact:true}).waitFor();
  }
  if(role==='finance'){await navigate('Financeiro');await page.getByText('Venda contratada',{exact:true}).waitFor();assert.match(await page.locator('main').innerText(),/5.600,00/);assert.equal(calls.some(c=>c.name==='get_event_operations'),false);assert.ok(calls.some(c=>c.name==='get_work_finance_index'));assert.ok(calls.some(c=>c.name==='get_work_finance'));assert.equal(calls.some(c=>c.name==='get_event_remunerations'),false);await capture('independent-finance')}
  if(role==='worker'){
   await navigate('Dashboard');const metric=label=>page.locator('.metric').filter({has:page.getByText(label,{exact:true})}).locator('strong');assert.equal(await metric('Trabalhos ativos').innerText(),'1');assert.equal(await metric('Trabalhos concluídos confirmados').innerText(),'1');assert.match(await metric('Recebido').innerText(),/440,00/);assert.equal(await page.getByText('Eventos ativos',{exact:true}).count(),0);await capture('worker-dashboard');
   await navigate('Minha escala');await page.getByRole('button',{name:'Aceitar condições revisão 2'}).click();await page.getByText('Condições aceitas.',{exact:true}).waitFor();await page.getByText(/Valor aceito a pagar: R\$\s*460,00/).waitFor();assert.match(await page.locator('main').innerText(),/Valor aceito a pagar: R\$\s*460,00/);await page.getByRole('button',{name:'Confirmar convocação'}).click();await page.getByText('Convocação confirmada.',{exact:true}).waitFor();await page.getByRole('button',{name:'Fazer check-in'}).click();await page.getByRole('button',{name:'Fazer check-out'}).click();await page.getByText('Check-out registrado.',{exact:true}).waitFor();await capture('own-work');await navigate('Dashboard');assert.equal(await metric('Trabalhos ativos').innerText(),'0','Check-out stops counting active work');assert.equal(await metric('Trabalhos concluídos confirmados').innerText(),'1','Check-out alone does not invent confirmed completion');assert.match(await metric('Recebido').innerText(),/440,00/);await navigate('Eventos');assert.match(await page.locator('.opportunityCard').innerText(),/07\/10\/2026/);assert.doesNotMatch(await page.locator('.opportunityCard').innerText(),/Trabalho privado|Endereço exato|Orientação privada|Requisito privado/);await page.getByRole('button',{name:'Tenho interesse'}).click();await capture('public-opportunities');
  }
  if(role==='coordinator'||role==='legacy'){
   await navigate('Início');await page.getByRole('button',{name:/^Abrir Trabalho privado Aurora/}).click();await page.locator('.operator h2').waitFor();assert.equal(await page.locator('.eventsGrid').count(),0);if(role==='coordinator'){assert.equal(await page.getByRole('button',{name:'Publicar vaga',exact:true}).count(),0,'Coordinator without finance cannot publish');assert.equal(await page.getByRole('button',{name:'Pagamentos',exact:true}).count(),0);assert.doesNotMatch(await page.locator('.operator').innerText(),/R\$|Diária|Resultado estimado/);assert.equal(calls.some(c=>['get_work_finance','get_event_remunerations','get_commercial_workspace'].includes(c.name)),false);await capture('operations-without-finance')}else{await page.getByRole('button',{name:'Pagamentos',exact:true}).click();assert.match(await page.locator('.operator').innerText(),/Venda histórica contratada; recebimento não informado/);await geometry();await capture('historical-finance');await page.getByRole('button',{name:'Voltar para meus eventos'}).click();await page.getByRole('button',{name:'Configurar atividade comercial',exact:true}).click();const setup=page.locator('#business-setup');await setup.locator('[name=name]').fill('Fornecedor histórico');await setup.locator('[name=document_number]').fill('529.982.247-25');await setup.getByRole('button',{name:'Salvar atividade comercial'}).click();await page.getByText('Identificação privada CPF · final 4725.',{exact:false}).waitFor();const original=calls.find(c=>c.name==='configure_business_identity');assert.equal(original.args.p_payload.organization_id,undefined);assert.equal(calls.some(c=>c.name==='events'&&c.method==='PATCH'),false)}
  }
  await navigate('Meu perfil');const enlarge=page.getByRole('link',{name:'Ampliar: Trabalho real',exact:true});await enlarge.waitFor();assert.equal(await enlarge.getAttribute('target'),'_blank');assert.equal(await enlarge.getAttribute('href'),image);await geometry();await page.screenshot({path:path.join(output,`${role}-${width}.png`),fullPage:true});
  assert.deepEqual(errors,[]);results.push({role,width,routes:routes.length,mutations:calls.filter(c=>c.method==='POST'&&!c.name.startsWith('get_')&&!c.name.startsWith('list_')).map(c=>c.name),status:'PASS'});console.log(JSON.stringify(results.at(-1)));await context.close();
 }
 await fs.writeFile(path.join(output,'results.json'),JSON.stringify(results,null,2));console.log(`PASS: ${results.length} role/viewport journeys`);
}finally{await browser?.close();server.kill()}
