-- Transactional audience/state tests; no adapters, external sends or persisted identities.
begin;
create function pg_temp.check_true(ok boolean,label text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception 'FAIL: %',label; end if; end $$;
create function pg_temp.expect_error(statement text,expected text) returns void language plpgsql as $$ begin begin execute statement; exception when others then if sqlerrm=expected then return; end if; raise; end; raise exception 'FAIL: unexpectedly allowed %',statement; end $$;
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) select
 ('95090000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,
 'commercial-alert-'||n||'@example.invalid',now(),jsonb_build_object('full_name','Commercial alert test '||n)
 from generate_series(1,6) n;
update public.profiles set active=true,onboarding_completed=true,profile_type='company' where id::text like '95090000-%';
set local role authenticated;
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000001',true);
select set_config('test.provider',public.configure_business_identity('{"display_name":"Private provider","organization_type":"team","market_role":"provider","document":"96385274128"}')::text,true);
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000002',true);
select set_config('test.buyer',public.configure_business_identity('{"display_name":"Private agency","organization_type":"agency","market_role":"buyer","buyer_subtype":"agency","document":"74185296355"}')::text,true);
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000003',true);
select set_config('test.foreign',public.configure_business_identity('{"display_name":"Foreign provider","organization_type":"team","market_role":"provider","document":"15975348625"}')::text,true);
reset role;
insert into public.organization_members(organization_id,profile_id,member_role,finance_authorized) values
 (current_setting('test.provider')::uuid,'95090000-0000-4000-8000-000000000004','manager',false),
 (current_setting('test.provider')::uuid,'95090000-0000-4000-8000-000000000005','member',true),
 (current_setting('test.buyer')::uuid,'95090000-0000-4000-8000-000000000006','member',true);
set local role authenticated;
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000002',true);
select set_config('test.request',public.create_contract_request(current_setting('test.buyer')::uuid,current_setting('test.provider')::uuid,'SECRET REQUEST CLIENT','SECRET DESCRIPTION',current_date+10,'SECRET VENUE')::text,true);
reset role;
select pg_temp.check_true((select count(*)=2 from public.notifications n join private.notification_events e on e.id=n.source_id where e.event_key='request:'||current_setting('test.request')),'new private request reaches provider owner and authorized finance member');
select pg_temp.check_true((select bool_and(n.profile_id in ('95090000-0000-4000-8000-000000000001','95090000-0000-4000-8000-000000000005')) from public.notifications n join private.notification_events e on e.id=n.source_id where e.event_key='request:'||current_setting('test.request')),'request excludes buyer, outsider and coordinator');
select set_config('test.request_source',(select id::text from private.notification_events where event_key='request:'||current_setting('test.request')),true);
set local role authenticated;
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000004',true);
select pg_temp.check_true(jsonb_array_length(public.get_notification_center()->'notifications')=0,'operational coordinator sees no commercial alert');
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000003',true);
select pg_temp.check_true(jsonb_array_length(public.get_notification_center()->'notifications')=0,'foreign company sees no private request');
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000001',true);
select pg_temp.check_true(public.get_notification_center()->'notifications'->0->>'link'='/?request='||current_setting('test.request'),'request opens its exact protected destination');
select pg_temp.check_true((public.get_notification_center()->'notifications')::text !~ 'SECRET|963852|freelancer_unit_cost|client_total|margin','request message contains no client, document or financial payload');
select set_config('test.quote',public.save_sale_quote(jsonb_build_object('organization_id',current_setting('test.provider'),'request_id',current_setting('test.request'),'title','SECRET QUOTE','valid_until',current_date+20,'payment_terms','SECRET PAYMENT','show_unit_prices',true),jsonb_build_array(jsonb_build_object('label','SECRET SERVICE','quantity',10,'contract_days',2,'client_unit_price',280,'freelancer_unit_cost',220)))::text,true);
reset role;
select pg_temp.check_true(not exists(select 1 from private.notification_events where event_key='proposal:'||current_setting('test.quote')),'draft does not create a proposal alert');
set local role authenticated;
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000001',true);
select public.submit_sale_quote(current_setting('test.quote')::uuid,1);
reset role;
select set_config('test.proposal_source',(select id::text from private.notification_events where event_key='proposal:'||current_setting('test.quote')),true);
select pg_temp.check_true((select count(*)=2 from public.notifications n join private.notification_events e on e.id=n.source_id where e.event_key='proposal:'||current_setting('test.quote')),'sent proposal reaches buyer owner and authorized finance member');
select pg_temp.check_true((select bool_and(n.profile_id in ('95090000-0000-4000-8000-000000000002','95090000-0000-4000-8000-000000000006')) from public.notifications n join private.notification_events e on e.id=n.source_id where e.event_key='proposal:'||current_setting('test.quote')),'proposal excludes sender, freelancer, coordinator and foreign company');
select private.eventcore_enqueue_notification('request:'||current_setting('test.request'),'request',current_setting('test.request')::uuid);
select private.eventcore_enqueue_notification('proposal:'||current_setting('test.quote'),'proposal',current_setting('test.quote')::uuid);
select pg_temp.check_true((select count(*)=4 from public.notifications n join private.notification_events e on e.id=n.source_id where e.event_key in ('request:'||current_setting('test.request'),'proposal:'||current_setting('test.quote'))),'request and proposal are durably deduplicated');
set local role authenticated;
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000002',true);
select pg_temp.check_true(public.get_notification_center()->'notifications'->0->>'link'='/?proposal='||current_setting('test.quote'),'buyer sees proposal destination');
select pg_temp.check_true((public.get_notification_center()->'notifications')::text !~ 'SECRET|client_total|client_unit_price|freelancer_unit_cost|margin','proposal message contains no sale, internal cost or client');
select public.save_notification_preferences('{"email_enabled":true,"push_enabled":false,"cadence":"immediate"}');
reset role;
select pg_temp.check_true(private.eventcore_notification_allowed(current_setting('test.proposal_source')::uuid,'95090000-0000-4000-8000-000000000002','email'),'unexpired sent proposal with enabled channel is eligible before state tests');
set local role authenticated;
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000001',true);
select set_config('test.sibling',public.save_sale_quote(jsonb_build_object('organization_id',current_setting('test.provider'),'request_id',current_setting('test.request'),'title','SECRET SIBLING','valid_until',current_date+20,'payment_terms','Test','show_unit_prices',true),jsonb_build_array(jsonb_build_object('label','Test','quantity',1,'contract_days',1,'client_unit_price',280)))::text,true);
select public.submit_sale_quote(current_setting('test.sibling')::uuid,1);
reset role;
select set_config('test.sibling_source',(select id::text from private.notification_events where event_key='proposal:'||current_setting('test.sibling')),true);
select pg_temp.check_true(private.eventcore_notification_allowed(current_setting('test.sibling_source')::uuid,'95090000-0000-4000-8000-000000000002','email'),'sibling is eligible while request is still quoted');
set local role authenticated;
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000001',true);
select set_config('test.client',public.create_external_work_client(current_setting('test.provider')::uuid,'SECRET EXTERNAL CLIENT')::text,true);
select set_config('test.external_quote',public.save_sale_quote(jsonb_build_object('organization_id',current_setting('test.provider'),'client_id',current_setting('test.client'),'title','SECRET EXTERNAL QUOTE','valid_until',current_date+20,'payment_terms','Test','show_unit_prices',false),jsonb_build_array(jsonb_build_object('label','Test','quantity',1,'contract_days',1,'client_unit_price',280)))::text,true);
select public.submit_sale_quote(current_setting('test.external_quote')::uuid,1);
reset role;
select pg_temp.check_true(not exists(select 1 from private.notification_events where event_key='proposal:'||current_setting('test.external_quote')),'external quote has no general dissemination');
select pg_temp.check_true(private.eventcore_notification_allowed(current_setting('test.proposal_source')::uuid,'95090000-0000-4000-8000-000000000002','email'),'unexpired proposal is eligible with confirmed email and enabled channel');
-- Expiration fixture only, inside rollback; never rewrite a real sent proposal.
set local session_replication_role=replica;
update public.proposals set valid_until=private.eventcore_business_today()-1 where id=current_setting('test.quote')::uuid;
set local session_replication_role=origin;
select pg_temp.check_true(not private.eventcore_notification_allowed(current_setting('test.proposal_source')::uuid,'95090000-0000-4000-8000-000000000002','email'),'expired proposal cannot send an external alert');
set local session_replication_role=replica;
update public.proposals set valid_until=current_date+20 where id=current_setting('test.quote')::uuid;
set local session_replication_role=origin;
set local role authenticated;
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000005',true);
select public.save_notification_preferences('{"mode":"relevant","regions":["unrelated"],"email_enabled":true,"push_enabled":false,"cadence":"immediate"}');
reset role;
select pg_temp.check_true(private.eventcore_notification_allowed(current_setting('test.request_source')::uuid,'95090000-0000-4000-8000-000000000005','email'),'specific private request ignores general opportunity region filter');
update private.notification_outbox q set available_at=now()-interval '1 minute' from public.notifications n
where n.id=q.notification_id and n.profile_id='95090000-0000-4000-8000-000000000002' and n.source_id=current_setting('test.sibling_source')::uuid and q.channel='email';
select set_config('request.jwt.claim.role','service_role',true);
select set_config('test.claims',public.claim_notification_batches(20)::text,true);
select set_config('test.claims_second',public.claim_notification_batches(20)::text,true);
select set_config('test.sibling_lease',(select x::text from jsonb_array_elements(current_setting('test.claims')::jsonb||current_setting('test.claims_second')::jsonb) x where x->>'channel'='email' and x->>'to'='commercial-alert-2@example.invalid' and x->'notifications' @> jsonb_build_array(jsonb_build_object('link','/?proposal='||current_setting('test.sibling'))) limit 1),true);
select pg_temp.check_true(nullif(current_setting('test.sibling_lease',true),'') is not null,'sibling proposal has an actual lease');
select pg_temp.check_true(public.recheck_notification_batch((current_setting('test.sibling_lease')::jsonb->>'id')::uuid,(current_setting('test.sibling_lease')::jsonb->>'lease_token')::uuid),'sibling has a valid actual lease before another proposal is accepted');
select set_config('test.lease',(select x::text from jsonb_array_elements(current_setting('test.claims')::jsonb) x where x->>'channel'='email' and x->>'to'='commercial-alert-5@example.invalid' limit 1),true);
select pg_temp.check_true(current_setting('test.lease',true) is not null,'authorized request has an actual database lease');
select pg_temp.check_true(public.recheck_notification_batch((current_setting('test.lease')::jsonb->>'id')::uuid,(current_setting('test.lease')::jsonb->>'lease_token')::uuid),'allowed request rechecks before send');
set local role authenticated;
select set_config('request.jwt.claim.role','authenticated',true);
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000001',true);
select public.set_organization_finance_member(current_setting('test.provider')::uuid,'95090000-0000-4000-8000-000000000005',false);
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000005',true);
select pg_temp.check_true(jsonb_array_length(public.get_notification_center()->'notifications')=0,'revoked finance member loses central access');
reset role;
select set_config('request.jwt.claim.role','service_role',true);
select pg_temp.check_true(not public.recheck_notification_batch((current_setting('test.lease')::jsonb->>'id')::uuid,(current_setting('test.lease')::jsonb->>'lease_token')::uuid),'revoked membership invalidates an already claimed send');
set local role authenticated;
select set_config('request.jwt.claim.role','authenticated',true);
select set_config('request.jwt.claim.sub','95090000-0000-4000-8000-000000000002',true);
select set_config('test.contract',public.accept_sale_quote(current_setting('test.quote')::uuid,1)::text,true);
reset role;
select pg_temp.check_true(not private.eventcore_notification_allowed(current_setting('test.proposal_source')::uuid,'95090000-0000-4000-8000-000000000002','email'),'accepted proposal cannot send a stale proposal alert');
select pg_temp.check_true(not private.eventcore_notification_allowed(current_setting('test.sibling_source')::uuid,'95090000-0000-4000-8000-000000000002','email'),'sibling proposal cannot alert after another proposal contracts the request');
select set_config('request.jwt.claim.role','service_role',true);
select pg_temp.check_true(not public.recheck_notification_batch((current_setting('test.sibling_lease')::jsonb->>'id')::uuid,(current_setting('test.sibling_lease')::jsonb->>'lease_token')::uuid),'request contracted by another proposal invalidates the sibling lease');
set local role authenticated;
select set_config('request.jwt.claim.role','authenticated',true);
select pg_temp.expect_error($q$select public.accept_sale_quote(current_setting('test.sibling')::uuid,1)$q$,'quote_not_available');
reset role;
select pg_temp.check_true(not private.eventcore_notification_allowed(current_setting('test.request_source')::uuid,'95090000-0000-4000-8000-000000000001'),'contracted request no longer asks for a quote');
select pg_temp.check_true((select count(*)=3 from public.notifications n join private.notification_events e on e.id=n.source_id where e.event_key='contract:'||current_setting('test.contract')),'existing contract confirmation still reaches authorized parties');
select pg_temp.check_true(private.eventcore_notification_allowed(current_setting('test.proposal_source')::uuid,'95090000-0000-4000-8000-000000000006'),'authorized buyer finance member retains accepted proposal in center');
update public.organization_members set finance_authorized=false where organization_id=current_setting('test.buyer')::uuid and profile_id='95090000-0000-4000-8000-000000000006';
select pg_temp.check_true(not private.eventcore_notification_allowed(current_setting('test.proposal_source')::uuid,'95090000-0000-4000-8000-000000000006'),'buyer member revocation removes accepted proposal visibility');
select pg_temp.check_true(not has_function_privilege('authenticated','private.eventcore_enqueue_notification(text,text,uuid)','execute'),'clients cannot enqueue arbitrary private sources');
rollback;
