"use client";

import { FormEvent, useEffect, useState } from "react";
import { freelancerDashboard, businessDashboard } from "@/lib/dashboard";
import { validateDocument } from "@/lib/identity";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase-browser";
import { AppTab, capabilitiesFor, canOpenTab, isStaff, navigationFor, profileTypeLabel, type ProfileType } from "@/lib/capabilities";

type Profile = {
  id:string; full_name:string|null; phone:string|null; role:string; active:boolean;
  profile_type:ProfileType; onboarding_completed:boolean; professional_status:string; bio?:string|null;
};
type Client = { id:string; trade_name:string; legal_name?:string|null; contact_name?:string|null; phone?:string|null; email?:string|null; active:boolean; organization_id?:string|null };
type Freelancer = { id:string; profile_id?:string|null; full_name:string; phone?:string|null; city?:string|null; active:boolean; rating:number; completed_jobs:number; no_show_count?:number };
type DirectoryProfessional = { freelancer_id:string; profile_id?:string|null; full_name:string; city?:string|null; rating:number; completed_jobs:number; review_count:number; specialties:string[] };
type Specialty = { id:string; slug:string; name:string; active:boolean; sort_order:number };
type Organization = { id:string; owner_profile_id:string; organization_type:"team"|"company"|"agency"; legal_name?:string|null; trade_name?:string|null; display_name:string; business_type?:string|null; active:boolean };
type EventRow = { id:string; client_id:string; name:string; venue:string; start_at:string; end_at?:string|null; status:string; arrival_tolerance_minutes:number; notes?:string|null; calendar_sync_status:string; google_event_id?:string|null; calendar_last_error?:string|null; created_by_profile_id?:string|null; organization_id?:string|null };
type EventService = { id:string; event_id:string; service_type:string; label:string; quantity_needed:number; reserve_target:number; freelancer_unit_cost?:number|null; briefing?:string|null; specialty_id?:string|null; visibility:string; application_enabled:boolean; requirements?:string|null };
type JobApplication = { id:string; event_service_id:string; freelancer_id:string; status:string; message?:string|null; created_at:string; updated_at:string };
type Assignment = { id:string; event_service_id:string; freelancer_id:string; status:string; agreed_amount?:number|null; contractor_profile_id?:string|null; application_id?:string|null; hired_at?:string|null; created_at?:string };
type Attendance = { id:string; assignment_id:string; check_in_at?:string|null; check_out_at?:string|null };
type Payment = { id:string; assignment_id:string; amount:number; status:string; method?:string|null; paid_at?:string|null; created_at?:string };
type Rating = { id:string; assignment_id:string; event_id:string; freelancer_id:string; reviewer_profile_id:string; rating:number; comment?:string|null; created_at:string };
type Integration = { id:string; kind:string; account_email?:string|null; status:string };
type EventPane = "equipe"|"candidaturas"|"escala"|"presenca"|"financeiro"|"avaliacoes";
type EventsMode = "mine"|"opportunities";

type Opportunity = {service_id:string;event_id:string;event_name:string;start_at:string;end_at:string|null;venue:string;function_name:string;specialty_id:string|null;vacancies:number;amount:number|null;contractor_name:string;requirements:string|null;event_status:string;compatible:boolean};
type RosterMember = {profile_id:string;full_name:string;phone:string|null;member_role:string;active:boolean};
type Reputation = {name:string;availability:string|null;bio:string|null;reviews:{id:string;rating:number;comment:string|null;date:string;event_name:string}[]};
type ProfilePayload = {profile_type:Exclude<ProfileType,null>;full_name:string;phone:string;document_type:"cpf"|"cnpj";document_number:string;specialty_ids:string[];organization_name:string;business_type:string;city:string;bio:string;professional_status:string};
function profilePayload(form:HTMLFormElement):ProfilePayload {
 const f=new FormData(form);return {profile_type:String(f.get("profile_type")) as Exclude<ProfileType,null>,full_name:String(f.get("full_name")||""),phone:String(f.get("phone")||""),document_type:String(f.get("document_type")) as "cpf"|"cnpj",document_number:String(f.get("document_number")||""),specialty_ids:f.getAll("specialty_ids").map(String),organization_name:String(f.get("organization_name")||""),business_type:String(f.get("business_type")||""),city:String(f.get("city")||""),bio:String(f.get("bio")||""),professional_status:String(f.get("professional_status")||"available")};
}
const eventStatus:Record<string,string>={planning:"Planejamento",staffing:"Montando equipe",confirmed:"Confirmado",in_progress:"Em andamento",completed:"Concluído",cancelled:"Cancelado"};
const assignmentStatus:Record<string,string>={invited:"Convidado",confirmed:"Confirmado",reserve:"Reserva",cancelled:"Cancelado",checked_in:"Em serviço",checked_out:"Concluído",no_show:"Ausente"};
const applicationStatus:Record<string,string>={interested:"Interesse enviado",shortlisted:"Pré-selecionado",accepted:"Contratado",rejected:"Não selecionado",withdrawn:"Retirado"};
const calendarStatus:Record<string,string>={not_linked:"Não sincronizado",pending:"Aguardando sincronização",synced:"Sincronizado",out_of_sync:"Atualização pendente",error:"Erro de sincronização"};
const paymentMethod:Record<string,string>={pix:"Pix",transfer:"Transferência",cash:"Dinheiro",other:"Outro"};
const paymentStatus:Record<string,string>={pending:"Pendente",approved:"Aprovado",paid:"Pago",held:"Em análise",cancelled:"Cancelado"};
const businessTypes=["Cenografia","Equipe de carregadores","Agência de eventos","Equipe técnica","Produção","Montagem","Logística","Segurança","Limpeza","Prestadora de serviços","Outro"];

function msg(e:unknown){ return e && typeof e==="object" && "message" in e ? String(e.message) : String(e); }
function friendlyError(e:unknown){const m=msg(e);const messages:Record<string,string>={private_document_conflict:"Confira os dados de identificação ou entre na sua conta existente.",invalid_private_document:"Confira o CPF/CNPJ e seus dígitos verificadores.",vacancies_filled:"As vagas desta função já foram preenchidas.",completed_validated_event_required:"Conclua o evento e valide a presença antes de avaliar.",assignment_already_rated:"Esta contratação já foi avaliada.",event_has_not_ended:"O horário de término do evento ainda não passou.",forbidden:"Seu perfil não tem permissão para esta ação.",profile_type_locked:"O tipo de um perfil concluído é mantido para preservar sua operação.",attendance_required:"Registre a presença antes de concluir a contratação.",invalid_attendance_transition:"Esta ação não está disponível para o status atual.",select_active_specialties:"Selecione ao menos uma especialidade.",self_hiring_not_allowed:"Não é possível contratar a própria conta.",specialty_not_compatible:"Esta vaga pede uma especialidade diferente do seu perfil."};return messages[m]||m;}
function brl(n:number){ return Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}); }
export default function Page(){
  const [session,setSession]=useState<Session|null>(null);
  const [profile,setProfile]=useState<Profile|null>(null);
  const [loading,setLoading]=useState(true);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  const [notice,setNotice]=useState("");
  const [signup,setSignup]=useState(false);
  const [tab,setTab]=useState<AppTab>("home");
  const [eventsMode,setEventsMode]=useState<EventsMode>("mine");
  const [eventPane,setEventPane]=useState<EventPane>("equipe");
  const [clients,setClients]=useState<Client[]>([]);
  const [directory,setDirectory]=useState<DirectoryProfessional[]>([]);
  const [ownFreelancer,setOwnFreelancer]=useState<Freelancer|null>(null);
  const [specialties,setSpecialties]=useState<Specialty[]>([]);
  const [mySpecialtyIds,setMySpecialtyIds]=useState<string[]>([]);
  const [organizations,setOrganizations]=useState<Organization[]>([]);
  const [events,setEvents]=useState<EventRow[]>([]);
  const [services,setServices]=useState<EventService[]>([]);
  const [applications,setApplications]=useState<JobApplication[]>([]);
  const [assignments,setAssignments]=useState<Assignment[]>([]);
  const [attendance,setAttendance]=useState<Attendance[]>([]);
  const [payments,setPayments]=useState<Payment[]>([]);
  const [ratings,setRatings]=useState<Rating[]>([]);
  const [profiles,setProfiles]=useState<Profile[]>([]);
  const [integration,setIntegration]=useState<Integration|null>(null);
  const [selectedEventId,setSelectedEventId]=useState<string|null>(null);
  const [opportunities,setOpportunities]=useState<Opportunity[]>([]);
  const [activeOrgId,setActiveOrgId]=useState("");
  const [roster,setRoster]=useState<RosterMember[]>([]);
  const [reputation,setReputation]=useState<Reputation|null>(null);
  const [editProfile,setEditProfile]=useState(false);
  const [authSpecialties,setAuthSpecialties]=useState<Specialty[]>([]);
  const [installPrompt,setInstallPrompt]=useState<any>(null);

  useEffect(()=>{
    if("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(()=>{});
    const handler=(e:any)=>{e.preventDefault();setInstallPrompt(e)};
    window.addEventListener("beforeinstallprompt",handler);
    const params=new URLSearchParams(location.search);
    if(params.get("google")==="connected"){setNotice("Google Calendar conectado com sucesso.");history.replaceState({},"","/")}
    if(params.get("google")==="error"){setError(params.get("message")||"Falha ao conectar o Google Calendar.");history.replaceState({},"","/")}
    fetch("/api/specialties").then(r=>r.json()).then(data=>{if(Array.isArray(data))setAuthSpecialties(data)}).catch(()=>{});
    supabase.auth.getSession().then(async({data})=>{if(data.session)await boot(data.session);else setLoading(false)});
    return()=>window.removeEventListener("beforeinstallprompt",handler);
  },[]);

  const caps=profile?capabilitiesFor(profile):null;
  const nav=profile?navigationFor(profile):[];
  const currentOrg=organizations.find(o=>o.id===activeOrgId)||organizations.find(o=>o.owner_profile_id===profile?.id)||organizations[0]||null;
  useEffect(()=>{if(currentOrg&&caps?.manageTeam)supabase.rpc("get_organization_roster",{p_organization_id:currentOrg.id}).then(({data,error})=>{if(error)setError(error.message);else setRoster(data||[])});else setRoster([])},[currentOrg?.id,profile?.id]);

  async function boot(s:Session){
    try{
      const {data:p,error:pe}=await supabase.from("profiles").select("id,full_name,phone,role,active,profile_type,onboarding_completed,professional_status,bio").eq("id",s.user.id).single();
      if(pe||!p||!p.active) throw new Error("Conta inativa ou sem perfil no EventCore.");
      const next=p as Profile; setSession(s);setProfile(next);
      if(!canOpenTab(next,tab))setTab("home");
      try{await loadAll(next)}catch(e){setError(friendlyError(e))}
    }catch(e){setError(msg(e));await supabase.auth.signOut()}finally{setLoading(false)}
  }

  async function loadAll(p:Profile=profile as Profile){
    if(!p)return;
    const c=capabilitiesFor(p);
    const base=await Promise.all([
      supabase.from("specialties").select("id,slug,name,active,sort_order").eq("active",true).order("sort_order"),
      supabase.from("profile_specialties").select("specialty_id").eq("profile_id",p.id),
      supabase.from("organizations").select("*").eq("active",true).order("created_at"),
      supabase.from("events").select("*").order("start_at"),
      supabase.from("event_services").select("*"),
      supabase.from("assignments").select("*").order("created_at",{ascending:false}),
      supabase.from("attendance").select("*"),
      supabase.from("payments").select("*"),
      supabase.from("job_applications").select("*").order("created_at",{ascending:false}),
      supabase.from("ratings").select("*").order("created_at",{ascending:false}),
    ]);
    for(const r of base){if(r.error)throw r.error}
    setSpecialties((base[0].data||[]) as Specialty[]);
    setMySpecialtyIds((base[1].data||[]).map((x:any)=>x.specialty_id));
    setOrganizations((base[2].data||[]) as Organization[]);
    setEvents((base[3].data||[]) as EventRow[]);
    setServices((base[4].data||[]) as EventService[]);
    setAssignments((base[5].data||[]) as Assignment[]);
    setAttendance((base[6].data||[]) as Attendance[]);
    setPayments((base[7].data||[]) as Payment[]);
    setApplications((base[8].data||[]) as JobApplication[]);
    setRatings((base[9].data||[]) as Rating[]);

    if(c.viewClients){const r=await supabase.from("clients").select("*").eq("active",true).order("trade_name");if(r.error)throw r.error;setClients((r.data||[]) as Client[])}else setClients([]);
    if(c.manageTeam||c.professional){const r=await supabase.rpc("get_professional_directory");if(r.error)throw r.error;setDirectory((r.data||[]) as DirectoryProfessional[])}else setDirectory([]);
    if(p.profile_type==="freelancer"){
      const r=await supabase.from("freelancers").select("id,profile_id,full_name,phone,city,active,rating,completed_jobs,no_show_count").eq("profile_id",p.id).maybeSingle();
      if(r.error)throw r.error;setOwnFreelancer((r.data||null) as Freelancer|null);
    }else setOwnFreelancer(null);
    const opp=await supabase.rpc("get_event_opportunities");if(opp.error)throw opp.error;setOpportunities((opp.data||[]) as Opportunity[]);
    if(c.manageCalendar){const r=await supabase.from("integrations").select("*").eq("kind","google_calendar").maybeSingle();if(r.error)throw r.error;setIntegration((r.data||null) as Integration|null)}else setIntegration(null);
    if(p.role==="admin"||p.role==="coordinator"){
      const r=await supabase.from("profiles").select("id,full_name,phone,role,active,profile_type,onboarding_completed,professional_status,bio").eq("active",true).order("full_name");if(r.error)throw r.error;setProfiles((r.data||[]) as Profile[])
    }else setProfiles([]);
  }

  async function login(e:FormEvent<HTMLFormElement>){
    e.preventDefault();const form=e.currentTarget;setBusy(true);setError("");setNotice("");
    const f=new FormData(form);const email=String(f.get("email")||"").trim();const password=String(f.get("password")||"");
    try{
      if(signup){
        const payload=profilePayload(form);
        if(!validateDocument(payload.document_type,payload.document_number))throw new Error("Confira o CPF/CNPJ informado.");
        if(!payload.specialty_ids.length)throw new Error("Selecione ao menos uma especialidade.");
        const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin,data:{full_name:payload.full_name,phone:payload.phone,profile_type:payload.profile_type}}});
        if(error)throw error;
        if(data.session){const done=await supabase.rpc("complete_profile",{p_payload:payload});if(done.error){await boot(data.session);throw done.error}await boot(data.session);setNotice("Conta criada. Seu EventCore está personalizado.")}
        else{form.reset();setSignup(false);setNotice("Confirme seu e-mail e entre para concluir o perfil. O CPF/CNPJ será salvo somente na área privada após a confirmação.")}
      }else{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error||!data.session)throw error||new Error("Falha no login");await boot(data.session)}
    }catch(e){setError(friendlyError(e))}finally{setBusy(false)}
  }

  async function logout(){await supabase.auth.signOut();location.reload()}
  async function refresh(){if(!profile)return;setBusy(true);setError("");try{await loadAll(profile)}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}

  async function completeOnboarding(payload:ProfilePayload){
    if(!profile)return;setBusy(true);setError("");
    try{const r=await supabase.rpc("complete_profile",{p_payload:payload});if(r.error)throw r.error;setEditProfile(false);await boot(session!);setNotice("Perfil atualizado. O EventCore foi personalizado para você.")}
    catch(e){setError(friendlyError(e))}finally{setBusy(false)}
  }
  async function action(work:()=>PromiseLike<{error:any}>,success:string){setBusy(true);setError("");try{const r=await work();if(r.error)throw r.error;setNotice(success);await loadAll()}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
  async function createClient(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);try{const payload:any={trade_name:String(f.get("trade_name")),contact_name:String(f.get("contact_name")||"")||null,phone:String(f.get("phone")||"")||null,email:String(f.get("email")||"")||null};if(currentOrg)payload.organization_id=currentOrg.id;const r=await supabase.from("clients").insert(payload);if(r.error)throw r.error;form.reset();setNotice("Cliente cadastrado.");await loadAll()}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
  async function createFreelancer(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);try{const r=await supabase.from("freelancers").insert({full_name:String(f.get("full_name")),phone:String(f.get("phone")||"")||null,city:String(f.get("city")||"Rio de Janeiro")});if(r.error)throw r.error;form.reset();setNotice("Profissional cadastrado.");await loadAll()}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
  async function createEvent(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile)return;const form=e.currentTarget;const f=new FormData(form);setBusy(true);try{const start=String(f.get("start_at"));const end=String(f.get("end_at")||"");const payload:any={client_id:String(f.get("client_id")),name:String(f.get("name")),venue:String(f.get("venue")),start_at:new Date(start).toISOString(),end_at:end?new Date(end).toISOString():null,status:String(f.get("status")||"confirmed"),coordinator_id:profile.id,created_by_profile_id:profile.id,arrival_tolerance_minutes:Number(f.get("tolerance")||15),notes:String(f.get("notes")||"")||null,calendar_sync_status:"pending"};if(currentOrg)payload.organization_id=currentOrg.id;const {data,error}=await supabase.from("events").insert(payload).select("*").single();if(error)throw error;form.reset();setSelectedEventId(data.id);setEventPane("equipe");setNotice("Evento criado.");await loadAll()}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
  async function createService(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedEventId)return;const form=e.currentTarget;const f=new FormData(form);setBusy(true);try{const specialtyId=String(f.get("specialty_id"));const specialty=specialties.find(s=>s.id===specialtyId);const legacy=specialty?.slug==="loader"?"loader":specialty?.slug==="security"?"security":specialty?.slug==="waiter"?"waiter":"other";const open=f.get("open_marketplace")==="on";const r=await supabase.from("event_services").insert({event_id:selectedEventId,service_type:legacy,label:specialty?.name||"Outro",specialty_id:specialtyId||null,quantity_needed:Number(f.get("quantity_needed")||1),reserve_target:Number(f.get("reserve_target")||0),freelancer_unit_cost:f.get("cost")?Number(f.get("cost")):null,briefing:String(f.get("briefing")||"")||null,requirements:String(f.get("requirements")||"")||null,visibility:open?"open":"private",application_enabled:open});if(r.error)throw r.error;const current=events.find(x=>x.id===selectedEventId);await supabase.from("events").update({calendar_sync_status:current?.google_event_id?"out_of_sync":"pending",updated_at:new Date().toISOString()}).eq("id",selectedEventId);form.reset();setNotice(open?"Vaga publicada no marketplace.":"Função adicionada ao evento.");await loadAll()}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
  async function createAssignment(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await action(()=>supabase.rpc("create_event_assignment",{p_service_id:String(f.get("event_service_id")),p_freelancer_id:String(f.get("freelancer_id")),p_status:String(f.get("status")||"invited"),p_amount:f.get("amount")?Number(f.get("amount")):null}),"Profissional incluído na escala.");}
  async function applyToService(o:Opportunity){await action(()=>supabase.rpc("apply_for_opportunity",{p_service_id:o.service_id}),"Interesse enviado ao contratante.");}
  async function withdrawApplication(app:JobApplication){setBusy(true);try{const r=await supabase.from("job_applications").update({status:"withdrawn",updated_at:new Date().toISOString()}).eq("id",app.id);if(r.error)throw r.error;setNotice("Candidatura retirada.");await loadAll()}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
  async function hireApplication(app:JobApplication){await action(()=>supabase.rpc("hire_application",{p_application_id:app.id}),"Contratação registrada. O profissional recebeu uma convocação.");}
  function position(){return new Promise<{lat:number;lng:number}>((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error("Geolocalização indisponível."));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude}),()=>reject(new Error("Permita acesso à localização.")),{enableHighAccuracy:true,timeout:12000,maximumAge:30000})})}
  async function presence(a:Assignment,kind:"in"|"out"){setBusy(true);setError("");try{const pos=await position();const r=await supabase.rpc("record_assignment_attendance",{p_assignment_id:a.id,p_kind:kind,p_lat:pos.lat,p_lng:pos.lng});if(r.error)throw r.error;setNotice(kind==="in"?"Check-in registrado.":"Check-out registrado.");await loadAll()}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
  async function respondAssignment(a:Assignment,status:"confirmed"|"cancelled"){setBusy(true);try{const r=await supabase.from("assignments").update({status,updated_at:new Date().toISOString()}).eq("id",a.id);if(r.error)throw r.error;setNotice(status==="confirmed"?"Presença confirmada.":"Convocação recusada.");await loadAll()}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
  async function pay(a:Assignment,method:string){await action(()=>supabase.rpc("mark_assignment_paid",{p_assignment_id:a.id,p_method:method}),"Pagamento registrado.");}
  async function rateAssignment(e:FormEvent<HTMLFormElement>,a:Assignment,eventId:string){e.preventDefault();const f=new FormData(e.currentTarget);await action(()=>supabase.rpc("submit_assignment_rating",{p_assignment_id:a.id,p_rating:Number(f.get("rating")),p_comment:String(f.get("comment")||"")}),"Avaliação registrada.");}
  async function viewReputation(id:string){const r=await supabase.rpc("get_professional_reputation",{p_freelancer_id:id});if(r.error)setError(friendlyError(r.error));else setReputation(r.data as Reputation);}
  async function linkAccount(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);try{const r=await supabase.from("freelancers").update({profile_id:String(f.get("profile_id")),updated_at:new Date().toISOString()}).eq("id",String(f.get("freelancer_id")));if(r.error)throw r.error;setNotice("Conta vinculada.");await loadAll()}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}

  async function connectGoogle(){if(!session)return;setBusy(true);setError("");try{const r=await fetch("/api/google/connect",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`}});const data=await r.json();if(!r.ok)throw new Error(data.error||"Falha ao iniciar Google OAuth");location.href=data.authorizeUrl}catch(e){setError(msg(e));setBusy(false)}}
  async function syncEvent(id:string){if(!session)return false;setBusy(true);setError("");try{const r=await fetch("/api/google/sync",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({eventId:id})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Falha ao sincronizar");setNotice("Evento sincronizado com o Google Calendar.");await loadAll();return true}catch(e){setError(msg(e));await supabase.from("events").update({calendar_sync_status:"error",calendar_last_error:msg(e),updated_at:new Date().toISOString()}).eq("id",id);await loadAll();return false}finally{setBusy(false)}}
  async function syncPending(){for(const ev of events.filter(e=>e.status!=="cancelled"&&e.end_at&&e.calendar_sync_status!=="synced")){await syncEvent(ev.id)}}

  const managedEvents=events.filter(e=>caps?.staff||e.organization_id===currentOrg?.id);
  const managedIds=new Set(managedEvents.map(e=>e.id));
  const managedServices=services.filter(s=>managedIds.has(s.event_id));
  const serviceIds=new Set(managedServices.map(s=>s.id));
  const managedAssignments=assignments.filter(a=>serviceIds.has(a.event_service_id));
  const assignmentIds=new Set(managedAssignments.map(a=>a.id));
  const scopedClients=clients.filter(c=>caps?.staff||c.organization_id===currentOrg?.id);
  const myAssignments=ownFreelancer?assignments.filter(a=>a.freelancer_id===ownFreelancer.id):[];
  const myIds=new Set(myAssignments.map(a=>a.id));
  const myPayments=payments.filter(p=>myIds.has(p.assignment_id));
  const myRatings=ratings.filter(r=>r.freelancer_id===ownFreelancer?.id);
  const myApplications=applications.filter(a=>a.freelancer_id===ownFreelancer?.id);
  const freelancerStats=freelancerDashboard({events,services,assignments:myAssignments,payments:myPayments,applications:myApplications,ratings:myRatings});
  const businessStats=businessDashboard({events:managedEvents,services:managedServices,assignments:managedAssignments,payments:payments.filter(p=>assignmentIds.has(p.assignment_id)),clients:scopedClients});
  const selectedEvent=managedEvents.find(e=>e.id===selectedEventId)||null;
  const selectedServices=services.filter(s=>s.event_id===selectedEventId);
  const selectedServiceIds=new Set(selectedServices.map(s=>s.id));
  const selectedAssignments=assignments.filter(a=>selectedServiceIds.has(a.event_service_id));
  const selectedApplications=applications.filter(a=>selectedServiceIds.has(a.event_service_id));
  const filteredOpportunities=opportunities.filter(o=>!caps?.professional||o.compatible);
  const activeEvents=managedEvents.filter(e=>!['completed','cancelled'].includes(e.status));
  const nameFor=(id:string)=>directory.find(f=>f.freelancer_id===id)?.full_name||ownFreelancer?.full_name||'Profissional';
  const openEvent=(id:string)=>{setTab('events');setEventsMode('mine');setSelectedEventId(id);setEventPane('equipe')};

  if(loading)return <div className="loading">Abrindo EventCore…</div>;
  if(!session||!profile)return <main className="loginShell"><section className={`loginCard ${signup?'signupCard':''}`}>
    <Brand/><p className="eyebrow">SUA OPERAÇÃO DE EVENTOS</p><h1>{signup?'Criar conta':'Entrar no EventCore'}</h1><p className="subtle">Conecte oportunidades, equipes e eventos.</p>
    <div className="switch"><button type="button" className={!signup?'active':''} onClick={()=>{setSignup(false);setError('')}}>Entrar</button><button type="button" className={signup?'active':''} onClick={()=>{setSignup(true);setError('')}}>Criar conta</button></div>
    <form className="form" onSubmit={login}>
      {signup&&<ProfileFields specialties={authSpecialties}/>}
      <label>E-mail<input className="input" type="email" name="email" autoComplete="email" required/></label>
      <label>Senha<input className="input" type="password" name="password" autoComplete={signup?'new-password':'current-password'} minLength={8} required/></label>
      {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}
      <button className="btn" disabled={busy||signup&&!authSpecialties.length}>{busy?'Aguarde…':signup?'Criar minha conta':'Entrar'}</button>
      {signup&&<small className="subtle">Seu CPF/CNPJ fica na área privada de identificação e não aparece no perfil profissional.</small>}
    </form>
  </section></main>;

  const profileLabel=isStaff(profile)?profile.role==='admin'?'Administrador':'Coordenador':profile.profile_type?profileTypeLabel[profile.profile_type]:'Complete seu perfil';
  const needsOnboarding=!profile.onboarding_completed||!isStaff(profile)&&!profile.profile_type;
  const assignmentCard=(a:Assignment)=>{
    const service=services.find(s=>s.id===a.event_service_id);const ev=events.find(e=>e.id===service?.event_id);const payment=payments.find(p=>p.assignment_id===a.id);const att=attendance.find(x=>x.assignment_id===a.id);
    return <article className="freelancerCard" key={a.id}><div className="cardTop"><div><small>{service?.label||'Função'}</small><h3>{ev?.name||'Evento'}</h3></div><span className="status">{assignmentStatus[a.status]}</span></div><p className="subtle">{ev?date(ev.start_at):'Data a confirmar'} · {ev?.venue}</p><p>{payment||a.agreed_amount!=null?brl(Number(payment?.amount??a.agreed_amount)): 'Valor a confirmar'} · {paymentStatus[payment?.status||'pending']}</p>{service?.briefing&&<p className="subtle">{service.briefing}</p>}<div className="actions">{['invited','reserve'].includes(a.status)&&<><button className="btn" disabled={busy} onClick={()=>respondAssignment(a,'confirmed')}>Confirmar convocação</button><button className="btn secondary" disabled={busy} onClick={()=>respondAssignment(a,'cancelled')}>Não posso ir</button></>}{a.status==='confirmed'&&!att?.check_in_at&&<button className="btn" disabled={busy} onClick={()=>presence(a,'in')}>Fazer check-in</button>}{a.status==='checked_in'&&!att?.check_out_at&&<button className="btn" disabled={busy} onClick={()=>presence(a,'out')}>Fazer check-out</button>}{a.status==='checked_out'&&<span className="done">Serviço concluído</span>}</div></article>
  };

  return <div className="app"><aside className="sidebar"><Brand/><nav aria-label="Navegação principal">{nav.map(n=><button key={n.id} className={tab===n.id?'active':''} onClick={()=>{setTab(n.id);setEditProfile(false)}}>{n.label}</button>)}</nav><div className="userbox"><strong>{profile.full_name}</strong><small>{profileLabel}</small></div><button className="btn ghost" onClick={logout}>Sair</button></aside>
    <main className="main"><header className="topbar"><div><p className="eyebrow">{profileLabel}</p><h1>{nav.find(n=>n.id===tab)?.label||'EventCore'}</h1><p className="subtle">{currentOrg?.display_name||'EventCore · Marujo Eventos'}</p></div><div className="topActions">{organizations.length>1&&<label className="orgSelect">Organização<select className="select" value={currentOrg?.id||''} onChange={e=>{setActiveOrgId(e.target.value);setSelectedEventId(null)}}>{organizations.map(o=><option key={o.id} value={o.id}>{o.display_name}</option>)}</select></label>}{installPrompt&&<button className="btn secondary" onClick={async()=>{await installPrompt.prompt();setInstallPrompt(null)}}>Instalar app</button>}<button className="btn secondary" onClick={refresh} disabled={busy}>Atualizar</button><button className="btn ghost" onClick={logout}>Sair da conta</button></div></header>
    {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}
    {needsOnboarding?<section className="panel onboarding"><p className="eyebrow">PERSONALIZE SUA EXPERIÊNCIA</p><h2>Complete seu perfil para personalizar o EventCore.</h2><p className="subtle">Sua conta e seus dados anteriores continuam vinculados.</p><ProfileForm profile={profile} specialties={specialties} ids={mySpecialtyIds} organization={currentOrg} busy={busy} submit={completeOnboarding}/></section>:<>

    {tab==='home'&&<><section className="welcome panel"><div><p className="eyebrow">{caps?.professional?'SEU PRÓXIMO TRABALHO':'SUA PRÓXIMA OPERAÇÃO'}</p><h2>Olá, {profile.full_name?.split(' ')[0]||'bem-vindo'}.</h2><p className="subtle">{caps?.professional?'Veja vagas compatíveis, responda às convocações e acompanhe seus recebimentos.':profile.profile_type==='team_lead'?'Organize sua equipe, acompanhe a escala e encontre novas oportunidades.':profile.profile_type==='agency'?'Conecte seus clientes às equipes e acompanhe cada evento.':'Acompanhe seus eventos, clientes e profissionais em um só lugar.'}</p></div><button className="btn" onClick={()=>{setTab('events');setEventsMode(caps?.professional?'opportunities':'mine')}}>{caps?.professional?'Explorar oportunidades':'Abrir meus eventos'}</button></section>
      <section className="metrics">{caps?.professional?<><Metric label="Próximas convocações" value={myAssignments.filter(a=>a.status==='invited').length} detail="aguardando sua resposta"/><Metric label="Vagas compatíveis" value={filteredOpportunities.filter(o=>o.vacancies>0).length} detail="com vagas disponíveis"/><Metric label="A receber de contratos futuros" value={brl(freelancerStats.upcomingIncome)} detail="convocações confirmadas"/></>:<><Metric label="Eventos ativos" value={activeEvents.length} detail="na sua operação"/><Metric label="Vagas preenchidas" value={businessStats.filledVacancies} detail={`${businessStats.vacancies} vagas criadas`}/><Metric label="Clientes" value={businessStats.clients} detail="base comercial"/></>}</section>
      <section className="panel"><h2>{caps?.professional?'Minha próxima escala':'Próximos eventos'}</h2>{caps?.professional?<div className="cardGrid">{myAssignments.filter(a=>!['cancelled','checked_out','no_show'].includes(a.status)).slice(0,4).map(assignmentCard)}{!myAssignments.some(a=>!['cancelled','checked_out','no_show'].includes(a.status))&&<Empty text="Você ainda não tem trabalhos na próxima escala."/>}</div>:activeEvents.length?activeEvents.slice(0,5).map(ev=><EventCard key={ev.id} ev={ev} services={services} assignments={assignments} open={()=>openEvent(ev.id)}/>):<Empty text="Crie seu primeiro evento para começar a montar a equipe."/>}</section>
      {caps?.manageCalendar&&<section className="panel integrationPanel"><div><h3>Google Calendar</h3><p className="subtle">{integration?.status==='connected'?`Conectado a ${integration.account_email||'sua conta Google'}`:'Conecte a agenda que você já usa.'}</p></div><div className="rowActions">{integration?.status!=='connected'?<button className="btn secondary" disabled={busy} onClick={connectGoogle}>Conectar Google Calendar</button>:<><button className="btn secondary" disabled={busy} onClick={syncPending}>Sincronizar pendentes</button><button className="btn ghost" disabled={busy} onClick={()=>action(async()=>{const r=await fetch('/api/google/disconnect',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`}});const d=await r.json();return {error:r.ok?null:new Error(d.error||'Falha ao desconectar')}} ,'Google Calendar desconectado.')}>Desconectar</button></>}</div></section>}
    </>}

    {tab==='dashboard'&&<><p className="subtle dashboardIntro">Indicadores calculados com os registros disponíveis na sua operação.</p><section className="metrics">{caps?.professional?<><Metric label="Recebido neste mês" value={brl(freelancerStats.paidThisMonth)} detail="pagamentos marcados como pagos"/><Metric label="Total recebido" value={brl(freelancerStats.paidTotal)} detail="histórico de pagamentos"/><Metric label="Contratos futuros a receber" value={brl(freelancerStats.upcomingIncome)} detail="trabalhos confirmados"/><Metric label="Trabalhos concluídos" value={freelancerStats.completedJobs} detail="contratações com check-out"/><Metric label="Candidaturas" value={freelancerStats.applications} detail="sem candidaturas retiradas"/><Metric label="Taxa de contratação" value={freelancerStats.hireRate==null?'—':`${freelancerStats.hireRate.toFixed(0)}%`} detail={freelancerStats.hireRate==null?'Envie uma candidatura para calcular.':'aceitas / candidaturas válidas'}/><Metric label="Avaliação média" value={freelancerStats.reviewAverage==null?'—':`${freelancerStats.reviewAverage.toFixed(1)} / 5`} detail={`${freelancerStats.reviewCount} avaliações reais`}/></>:<><Metric label="Eventos ativos" value={businessStats.activeEvents} detail="planejamento ou execução"/><Metric label="Eventos concluídos" value={businessStats.completedEvents} detail="histórico de operações"/><Metric label="Vagas criadas" value={businessStats.vacancies} detail="funções de seus eventos"/><Metric label="Vagas preenchidas" value={businessStats.filledVacancies} detail="convocados e contratados"/><Metric label="Custo contratado" value={brl(businessStats.costs)} detail="pagamentos não cancelados"/><Metric label="Total pago" value={brl(businessStats.paidCosts)} detail="pagamentos marcados como pagos"/><Metric label="Clientes ativos" value={businessStats.clients} detail="sua base comercial"/></>}</section><div className="twoEqual">{caps?.professional?<><BarChart title="Recebimentos por mês" months={freelancerStats.months} field="paid" currency/><BarChart title="Trabalhos por mês" months={freelancerStats.months} field="jobs"/></>:<><BarChart title="Eventos por mês" months={businessStats.months} field="events"/><BarChart title="Pagamentos por mês" months={businessStats.months} field="cost" currency/></>}</div></>}

    {tab==='clients'&&caps?.viewClients&&<section className="twoCol"><div className="panel"><h2>Seus clientes</h2>{scopedClients.length?<div className="simpleList">{scopedClients.map(c=><article key={c.id}><strong>{c.trade_name}</strong><span>{[c.contact_name,c.phone,c.email].filter(Boolean).join(' · ')||'Sem contato informado'}</span></article>)}</div>:<Empty text="Nenhum cliente cadastrado."/>}</div><form className="panel form" onSubmit={createClient}><h2>Novo cliente</h2><label>Nome do cliente<input className="input" name="trade_name" required maxLength={150}/></label><label>Responsável<input className="input" name="contact_name"/></label><label>Telefone<input className="input" name="phone" type="tel"/></label><label>E-mail<input className="input" name="email" type="email"/></label><button className="btn" disabled={busy}>Cadastrar cliente</button></form></section>}

    {tab==='team'&&caps?.manageTeam&&<><section className="panel"><h2>{profile.profile_type==='team_lead'?'Minha equipe':'Profissionais'}</h2><p className="subtle">Especialidades e reputação calculadas a partir de trabalhos registrados.</p><div className="cardGrid">{directory.map(f=><article className="professionalCard" key={f.freelancer_id}><h3>{f.full_name}</h3><p className="subtle">{f.specialties.join(' · ')||'Especialidades ainda não informadas'}{f.city?` · ${f.city}`:''}</p><p>{f.review_count?`★ ${Number(f.rating).toFixed(1)} · ${f.review_count} avaliações`:'Sem avaliações'} · {f.completed_jobs} trabalhos concluídos</p><button className="btn secondary" onClick={()=>viewReputation(f.freelancer_id)}>Ver perfil profissional</button></article>)}</div>{!directory.length&&<Empty text="Nenhum profissional disponível na base."/>}</section>
      {currentOrg&&<section className="panel integrationPanel"><div><h3>Vínculos com {currentOrg.display_name}</h3>{roster.filter(m=>m.active).map(m=><div className="operationRow" key={m.profile_id}><div><strong>{m.full_name}</strong><span>{m.member_role==='owner'?'Responsável':m.member_role==='manager'?'Gestor':'Membro'}</span></div>{m.member_role==='member'&&<button className="btn ghost" disabled={busy} onClick={()=>action(()=>supabase.rpc('set_organization_member',{p_organization_id:currentOrg.id,p_profile_id:m.profile_id,p_active:false}),'Vínculo removido.').then(()=>setRoster(r=>r.filter(x=>x.profile_id!==m.profile_id)))}>Remover vínculo</button>}</div>)}</div><form className="form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const id=String(f.get('member'));await action(()=>supabase.rpc('set_organization_member',{p_organization_id:currentOrg.id,p_profile_id:id,p_active:true}),'Profissional vinculado à organização.');const r=await supabase.rpc('get_organization_roster',{p_organization_id:currentOrg.id});if(r.data)setRoster(r.data)}}><label>Vincular profissional<select className="select" name="member" required><option value="">Selecione</option>{directory.filter(f=>f.profile_id&&f.profile_id!==profile.id&&!roster.some(m=>m.profile_id===f.profile_id&&m.active)).map(f=><option key={f.freelancer_id} value={f.profile_id!}>{f.full_name}</option>)}</select></label><button className="btn" disabled={busy}>Adicionar à equipe</button></form></section>}
      {caps?.staff&&<div className="twoEqual"><form className="panel form" onSubmit={createFreelancer}><h3>Cadastro operacional</h3><label>Nome<input className="input" name="full_name" required/></label><label>Telefone<input className="input" name="phone" type="tel"/></label><label>Cidade<input className="input" name="city"/></label><button className="btn" disabled={busy}>Cadastrar profissional</button></form><form className="panel form" onSubmit={linkAccount}><h3>Vincular conta existente</h3><label>Profissional<select className="select" name="freelancer_id" required><option value="">Selecione</option>{directory.filter(f=>!f.profile_id).map(f=><option key={f.freelancer_id} value={f.freelancer_id}>{f.full_name}</option>)}</select></label><label>Conta<select className="select" name="profile_id" required><option value="">Selecione</option>{profiles.filter(p=>p.role==='freelancer').map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label><button className="btn" disabled={busy}>Vincular</button></form></div>}
    </>}

    {tab==='events'&&<>
      {caps?.manageEvents&&<div className="switch eventsSwitch"><button className={eventsMode==='mine'?'active':''} onClick={()=>setEventsMode('mine')}>Meus eventos</button><button className={eventsMode==='opportunities'?'active':''} onClick={()=>setEventsMode('opportunities')}>Oportunidades</button></div>}
      {(!caps?.manageEvents||eventsMode==='opportunities')?<><section className="panel"><div className="sectionHead"><div><h2>{caps?.professional?'Oportunidades para suas especialidades':'Oportunidades'}</h2><p className="subtle">{caps?.professional?'Demonstre interesse e acompanhe a resposta do contratante.':'Vagas abertas no EventCore. As candidaturas são enviadas pelas contas dos profissionais.'}</p></div></div><div className="cardGrid">{filteredOpportunities.map(o=>{const app=myApplications.find(a=>a.event_service_id===o.service_id);return <article className="opportunityCard" key={o.service_id}><div className="cardTop"><span className="status">{o.vacancies} vagas</span><small>{eventStatus[o.event_status]}</small></div><h3>{o.event_name}</h3><strong>{o.function_name}</strong><p className="subtle">{date(o.start_at)} · {o.venue}</p><p>{o.amount!=null?brl(Number(o.amount)):'Valor a combinar'} · {o.contractor_name}</p>{o.requirements&&<p className="subtle">Requisitos: {o.requirements}</p>}{caps?.applyForJobs&&(app&&app.status!=='withdrawn'?<div className="actions"><span className="done">{applicationStatus[app.status]}</span>{['interested','shortlisted'].includes(app.status)&&<button className="btn ghost" disabled={busy} onClick={()=>withdrawApplication(app)}>Retirar candidatura</button>}</div>:<button className="btn" disabled={busy||o.vacancies===0} onClick={()=>applyToService(o)}>{o.vacancies?'Tenho interesse':'Vagas preenchidas'}</button>)}</article>})}</div>{!filteredOpportunities.length&&<Empty text="Não há vagas abertas para este perfil no momento."/>}</section>
      {caps?.professional&&<section className="panel integrationPanel"><div><h3>Minhas candidaturas</h3>{myApplications.length?myApplications.map(a=><div className="operationRow" key={a.id}><div><strong>{opportunities.find(o=>o.service_id===a.event_service_id)?.event_name||services.find(s=>s.id===a.event_service_id)?.label||'Oportunidade'}</strong><span>{applicationStatus[a.status]} · {date(a.created_at)}</span></div>{['interested','shortlisted'].includes(a.status)&&<button className="btn secondary" disabled={busy} onClick={()=>withdrawApplication(a)}>Retirar</button>}</div>):<Empty text="Você ainda não enviou candidaturas."/>}</div></section>}
      </>:<><div className="eventsGrid"><section className="panel"><h2>Meus eventos</h2>{managedEvents.length?managedEvents.map(ev=><EventCard key={ev.id} ev={ev} services={services} assignments={assignments} open={()=>openEvent(ev.id)}/>):<Empty text="Nenhum evento cadastrado."/>}</section><form className="panel form" onSubmit={createEvent}><h2>Novo evento</h2><label>Nome do evento<input className="input" name="name" required/></label><label>Cliente<select className="select" name="client_id" required><option value="">Selecione</option>{scopedClients.map(c=><option key={c.id} value={c.id}>{c.trade_name}</option>)}</select></label><label>Local<input className="input" name="venue" required/></label><div className="formGrid"><label>Início<input className="input" name="start_at" type="datetime-local" required/></label><label>Término<input className="input" name="end_at" type="datetime-local" required/></label></div><label>Status<select className="select" name="status" defaultValue="planning"><option value="planning">Planejamento</option><option value="staffing">Montando equipe</option><option value="confirmed">Confirmado</option></select></label><label>Tolerância de chegada (min)<input className="input" name="tolerance" type="number" defaultValue={15} min={0} max={180}/></label><label>Observações internas<textarea className="textarea" name="notes"/></label><button className="btn" disabled={busy||!scopedClients.length}>Criar evento</button>{!scopedClients.length&&<small className="subtle">Cadastre um cliente primeiro.</small>}</form></div>
      {selectedEvent&&<section className="operator"><div className="operatorHead"><div><p className="eyebrow">OPERAÇÃO DO EVENTO</p><h2>{selectedEvent.name}</h2><p className="subtle">{date(selectedEvent.start_at)} · {selectedEvent.venue}</p></div><div className="rowActions">{caps?.manageCalendar&&<button className="btn secondary" disabled={busy||!selectedEvent.end_at} onClick={()=>syncEvent(selectedEvent.id)}>Sincronizar Google</button>}<label>Status<select className="select" aria-label="Status do evento" value={selectedEvent.status} disabled={busy} onChange={e=>action(()=>supabase.from('events').update({status:e.target.value,updated_at:new Date().toISOString()}).eq('id',selectedEvent.id),'Status atualizado.')}>{Object.entries(eventStatus).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button className="btn ghost" onClick={()=>setSelectedEventId(null)}>Fechar</button></div></div>
        <nav className="eventTabs" aria-label="Etapas do evento">{(['equipe','candidaturas','escala','presenca','financeiro','avaliacoes'] as EventPane[]).map(p=><button key={p} className={eventPane===p?'active':''} onClick={()=>setEventPane(p)}>{({equipe:'Funções e vagas',candidaturas:'Candidaturas',escala:'Escala',presenca:'Presença',financeiro:'Pagamentos',avaliacoes:'Avaliações'})[p]}</button>)}</nav>
        {eventPane==='equipe'&&<div className="operatorGrid"><form className="panel form" onSubmit={createService}><h3>Adicionar função</h3><label>Especialidade<select className="select" name="specialty_id" required>{specialties.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="formGrid"><label>Vagas<input className="input" type="number" name="quantity_needed" min={1} defaultValue={1} required/></label><label>Reservas<input className="input" type="number" name="reserve_target" min={0} defaultValue={0}/></label></div><label>Valor por profissional (R$)<input className="input" type="number" name="cost" min={0} step="0.01"/></label><label>Briefing da equipe<textarea className="textarea" name="briefing"/></label><label>Requisitos da vaga<textarea className="textarea" name="requirements"/></label><label className="checkLabel"><input type="checkbox" name="open_marketplace"/>Publicar em Oportunidades</label><button className="btn" disabled={busy||['completed','cancelled'].includes(selectedEvent.status)}>Adicionar função</button></form><div className="panel"><h3>Funções do evento</h3>{selectedServices.map(s=><div className="operationRow" key={s.id}><div><strong>{s.label}</strong><span>{s.quantity_needed} vagas · {s.reserve_target} reservas · {s.freelancer_unit_cost!=null?brl(Number(s.freelancer_unit_cost)):'Valor a confirmar'}</span><span>{s.visibility==='open'&&s.application_enabled?'Vaga aberta em Oportunidades':'Equipe privada'}</span></div><button className="btn secondary" disabled={busy} onClick={()=>action(()=>supabase.from('event_services').update({visibility:s.visibility==='open'?'private':'open',application_enabled:s.visibility!=='open'}).eq('id',s.id),'Publicação da vaga atualizada.')}>{s.visibility==='open'?'Fechar vaga':'Publicar vaga'}</button></div>)}{!selectedServices.length&&<Empty text="Adicione as funções e a quantidade de vagas."/>}</div></div>}
        {eventPane==='candidaturas'&&<div className="panel"><h3>Candidaturas recebidas</h3>{selectedApplications.map(a=><div className="operationRow" key={a.id}><div><strong>{nameFor(a.freelancer_id)}</strong><span>{services.find(s=>s.id===a.event_service_id)?.label} · {applicationStatus[a.status]}</span></div><div className="rowActions"><button className="btn secondary" onClick={()=>viewReputation(a.freelancer_id)}>Ver reputação</button>{['interested','shortlisted'].includes(a.status)&&<button className="btn" disabled={busy} onClick={()=>hireApplication(a)}>Contratar</button>}</div></div>)}{!selectedApplications.length&&<Empty text="Ainda não há candidaturas para este evento."/>}</div>}
        {eventPane==='escala'&&<div className="operatorGrid"><form className="panel form" onSubmit={createAssignment}><h3>Escalar profissional</h3><label>Função<select className="select" name="event_service_id" required>{selectedServices.map(s=><option key={s.id} value={s.id}>{s.label} · {s.quantity_needed} vagas</option>)}</select></label><label>Profissional<select className="select" name="freelancer_id" required><option value="">Selecione</option>{directory.filter(f=>f.profile_id!==profile.id).map(f=><option key={f.freelancer_id} value={f.freelancer_id}>{f.full_name}</option>)}</select></label><label>Status<select className="select" name="status" defaultValue="invited"><option value="invited">Convidado</option><option value="confirmed">Confirmado</option><option value="reserve">Reserva</option></select></label><label>Valor acordado (R$)<input className="input" type="number" name="amount" min={0} step="0.01"/></label><button className="btn" disabled={busy||!selectedServices.length||!directory.length}>Adicionar à escala</button></form><div className="panel"><h3>Escala atual</h3>{selectedAssignments.map(a=><div className="operationRow" key={a.id}><div><strong>{nameFor(a.freelancer_id)}</strong><span>{services.find(s=>s.id===a.event_service_id)?.label} · {assignmentStatus[a.status]}</span></div><span>{a.agreed_amount!=null?brl(Number(a.agreed_amount)):'Valor a confirmar'}</span></div>)}{!selectedAssignments.length&&<Empty text="Nenhum profissional escalado."/>}</div></div>}
        {eventPane==='presenca'&&<div className="panel"><h3>Check-in e check-out</h3>{selectedAssignments.filter(a=>!['reserve','cancelled','no_show'].includes(a.status)).map(a=>{const att=attendance.find(x=>x.assignment_id===a.id) as (Attendance&{validated_by?:string|null})|undefined;return <div className="operationRow" key={a.id}><div><strong>{nameFor(a.freelancer_id)}</strong><span>{assignmentStatus[a.status]}{att?.check_in_at?` · Entrada ${date(att.check_in_at)}`:''}{att?.check_out_at?` · Saída ${date(att.check_out_at)}`:''}</span></div><div className="rowActions">{a.status==='confirmed'&&<button className="btn" disabled={busy} onClick={()=>presence(a,'in')}>Check-in</button>}{a.status==='checked_in'&&<button className="btn secondary" disabled={busy} onClick={()=>presence(a,'out')}>Check-out</button>}{att?.check_out_at&&!att.validated_by&&<button className="btn" disabled={busy} onClick={()=>action(()=>supabase.rpc('validate_assignment_attendance',{p_assignment_id:a.id}),'Presença validada.')}>Validar presença</button>}{att?.validated_by&&att.check_out_at&&<span className="done">Presença validada</span>}</div></div>})}{!selectedAssignments.length&&<Empty text="Monte a escala para registrar a presença."/>}</div>}
        {eventPane==='financeiro'&&<div className="panel"><h3>Pagamentos da equipe</h3>{selectedAssignments.filter(a=>!['cancelled','reserve'].includes(a.status)).map(a=>{const p=payments.find(p=>p.assignment_id===a.id);return <div className="operationRow" key={a.id}><div><strong>{nameFor(a.freelancer_id)}</strong><span>{brl(Number(p?.amount??a.agreed_amount??0))} · {paymentStatus[p?.status||'pending']}</span></div><div className="rowActions">{p?.status==='paid'?<span className="done">Pago · {paymentMethod[p.method||'other']}</span>:<>{(['pix','transfer','cash'] as const).map(method=><button key={method} className="btn secondary" disabled={busy} onClick={()=>pay(a,method)}>{paymentMethod[method]}</button>)}</>}</div></div>})}{!selectedAssignments.length&&<Empty text="Os pagamentos aparecem após a contratação."/>}</div>}
        {eventPane==='avaliacoes'&&<div className="panel"><h3>Avaliar os profissionais</h3><p className="subtle">Disponível após concluir o evento, registrar o check-out e validar a presença.</p>{selectedAssignments.filter(a=>a.status==='checked_out').map(a=>{const rating=ratings.find(r=>r.assignment_id===a.id);const valid=attendance.some(x=>x.assignment_id===a.id&&x.check_out_at&&(x as Attendance&{validated_by?:string}).validated_by);return <div className="ratingRow" key={a.id}><h4>{nameFor(a.freelancer_id)}</h4>{rating?<p>★ {rating.rating}/5{rating.comment?` · ${rating.comment}`:''}</p>:<form className="ratingForm" onSubmit={e=>rateAssignment(e,a,selectedEvent.id)}><label>Nota<select className="select" name="rating" defaultValue="5">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} {n===1?'estrela':'estrelas'}</option>)}</select></label><label>Comentário opcional<input className="input" name="comment" maxLength={1000}/></label><button className="btn" disabled={busy||selectedEvent.status!=='completed'||!valid}>Registrar avaliação</button></form>}</div>})}{!selectedAssignments.some(a=>a.status==='checked_out')&&<Empty text="Nenhum trabalho com check-out registrado neste evento."/>}</div>}
      </section>}</>}
    </>}

    {tab==='schedule'&&caps?.professional&&<section className="cardGrid">{myAssignments.length?myAssignments.map(assignmentCard):<Empty text="Sua escala ainda está vazia."/>}</section>}
    {tab==='finance'&&<section className="panel"><h2>{caps?.professional?'Meus recebimentos':'Pagamentos da operação'}</h2>{(caps?.professional?myPayments:payments.filter(p=>assignmentIds.has(p.assignment_id))).map(p=>{const a=assignments.find(a=>a.id===p.assignment_id);const service=services.find(s=>s.id===a?.event_service_id);return <div className="operationRow" key={p.id}><div><strong>{caps?.professional?events.find(e=>e.id===service?.event_id)?.name||'Trabalho contratado':a?nameFor(a.freelancer_id):'Profissional'}</strong><span>{paymentStatus[p.status]}{p.paid_at?` · ${date(p.paid_at)}`:''}</span></div><strong>{brl(Number(p.amount))}</strong></div>})}{!(caps?.professional?myPayments:payments.filter(p=>assignmentIds.has(p.assignment_id))).length&&<Empty text="Não há pagamentos registrados."/>}</section>}
    {tab==='reputation'&&caps?.professional&&<section className="panel"><h2>Minha reputação profissional</h2><p>{freelancerStats.reviewCount?`★ ${freelancerStats.reviewAverage?.toFixed(1)}/5 · ${freelancerStats.reviewCount} avaliações`:'Você ainda não recebeu avaliações.'}</p><p className="subtle">{mySpecialtyIds.map(id=>specialties.find(s=>s.id===id)?.name).filter(Boolean).join(' · ')}</p>{myRatings.map(r=><article className="ratingRow" key={r.id}><strong>★ {r.rating}/5 · {events.find(e=>e.id===r.event_id)?.name||'Evento concluído'}</strong><p className="subtle">{date(r.created_at)}</p>{r.comment&&<p>{r.comment}</p>}</article>)}</section>}
    {tab==='profile'&&<section className="panel onboarding"><div className="sectionHead"><h2>Meu perfil</h2>{!editProfile&&<button className="btn secondary" onClick={()=>setEditProfile(true)}>Editar perfil</button>}</div>{editProfile?<ProfileForm profile={profile} specialties={specialties} ids={mySpecialtyIds} organization={currentOrg} busy={busy} submit={completeOnboarding}/>:<div className="simpleList"><article><strong>{profile.full_name}</strong><span>{profileLabel} · {session.user.email}</span></article><article><strong>Especialidades</strong><span>{mySpecialtyIds.map(id=>specialties.find(s=>s.id===id)?.name).filter(Boolean).join(' · ')||'Ainda não informadas'}</span></article>{currentOrg&&<article><strong>{currentOrg.display_name}</strong><span>{currentOrg.business_type}</span></article>}<article><strong>Disponibilidade</strong><span>{availability(profile.professional_status)}</span></article>{profile.bio&&<article><strong>Apresentação</strong><span>{profile.bio}</span></article>}<p className="subtle">Sua identificação CPF/CNPJ é privada.</p></div>}</section>}
    </>}
    {reputation&&<div className="modalBackdrop" onClick={()=>setReputation(null)}><section className="panel reputationModal" role="dialog" aria-modal="true" aria-labelledby="reputation-name" onClick={e=>e.stopPropagation()}><div className="sectionHead"><h2 id="reputation-name">{reputation.name}</h2><button className="btn ghost" onClick={()=>setReputation(null)}>Fechar</button></div><p className="subtle">{availability(reputation.availability||'')}</p>{reputation.bio&&<p>{reputation.bio}</p>}{reputation.reviews.length?reputation.reviews.map(r=><article className="ratingRow" key={r.id}><strong>★ {r.rating}/5 · {r.event_name}</strong><small className="subtle"> {date(r.date)}</small>{r.comment&&<p>{r.comment}</p>}</article>):<Empty text="Este profissional ainda não recebeu avaliações."/>}</section></div>}
    </main><nav className="mobileNav" aria-label="Navegação móvel">{nav.map(n=><button key={n.id} className={tab===n.id?'active':''} onClick={()=>{setTab(n.id);setEditProfile(false)}}>{n.label}</button>)}</nav>
  </div>;
}

function date(value:string){return new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}
function availability(value:string){return ({available:'Disponível para trabalhos',busy:'Em trabalho',unavailable:'Indisponível no momento'} as Record<string,string>)[value]||'Disponibilidade não informada'}
function Brand(){return <div className="brand"><div className="logo">EC</div><div><strong>EventCore</strong><small>Marujo Eventos</small></div></div>}
function Metric({label,value,detail}:{label:string;value:number|string;detail:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function Empty({text}:{text:string}){return <div className="empty"><span>{text}</span></div>}
function EventCard({ev,services,assignments,open}:{ev:EventRow;services:EventService[];assignments:Assignment[];open:()=>void}){
  const sv=services.filter(s=>s.event_id===ev.id);const ids=new Set(sv.map(s=>s.id));const need=sv.reduce((n,s)=>n+s.quantity_needed,0);const filled=assignments.filter(a=>ids.has(a.event_service_id)&&['invited','confirmed','checked_in','checked_out'].includes(a.status)).length;
  return <button className="eventCard" onClick={open}><div><strong>{ev.name}</strong><span>{ev.venue}</span></div><div><strong>{date(ev.start_at)}</strong><span>{eventStatus[ev.status]}</span></div><div><strong>{filled}/{need}</strong><span>vagas preenchidas</span></div><span className="status">{calendarStatus[ev.calendar_sync_status]||'Agenda'}</span></button>
}
function BarChart({title,months,field,currency=false}:{title:string;months:{key:string;label:string;paid:number;jobs:number;cost:number;events:number}[];field:'paid'|'jobs'|'cost'|'events';currency?:boolean}){
 const max=Math.max(1,...months.map(m=>m[field]));const empty=months.every(m=>m[field]===0);
 return <section className="panel"><h3>{title}</h3>{empty&&<p className="subtle">Sem registros nos últimos seis meses.</p>}<div className="barChart" role="img" aria-label={`${title}: ${months.map(m=>`${m.label} ${currency?brl(m[field]):m[field]}`).join(', ')}`}>{months.map(m=><div className="barColumn" key={m.key}><span className="barValue">{currency?brl(m[field]):m[field]}</span><div className="barTrack"><div className="bar" style={{height:`${m[field]/max*100}%`}}/></div><small>{m.label}</small></div>)}</div></section>
}
function ProfileFields({specialties,profile,ids=[],organization}:{specialties:Specialty[];profile?:Profile;ids?:string[];organization?:Organization|null}){
 const [kind,setKind]=useState<Exclude<ProfileType,null>>(profile?.profile_type||'freelancer');const [docType,setDocType]=useState<'cpf'|'cnpj'>(kind==='company'||kind==='agency'?'cnpj':'cpf');const locked=!!profile?.onboarding_completed&&!!profile?.profile_type;
 return <><label>Como você usa o EventCore?<select className="select" name="profile_type" value={kind} onChange={e=>{const k=e.target.value as Exclude<ProfileType,null>;setKind(k);setDocType(k==='company'||k==='agency'?'cnpj':'cpf')}}>{Object.entries(profileTypeLabel).map(([k,v])=><option key={k} value={k} disabled={locked&&k!==kind}>{v}</option>)}</select></label><label>{kind==='freelancer'?'Nome completo':'Nome do responsável'}<input className="input" name="full_name" defaultValue={profile?.full_name||''} autoComplete="name" required minLength={2} maxLength={150}/></label><label>Telefone<input className="input" name="phone" defaultValue={profile?.phone||''} type="tel" autoComplete="tel" maxLength={30}/></label>
 {kind!=='freelancer'&&<><label>{kind==='team_lead'?'Nome da equipe':kind==='agency'?'Nome da agência':'Nome da empresa'}<input className="input" name="organization_name" defaultValue={organization?.display_name||''} required minLength={2} maxLength={150}/></label><label>Área de atuação<select className="select" name="business_type" defaultValue={organization?.business_type||''} required><option value="">Selecione</option>{businessTypes.map(b=><option key={b}>{b}</option>)}</select></label></>}
 <fieldset className="specialtyField"><legend>{kind==='freelancer'?'Suas especialidades':'Especialidades da operação'}</legend><div className="specialtyGrid">{specialties.map(s=><label className="checkLabel" key={s.id}><input type="checkbox" name="specialty_ids" value={s.id} defaultChecked={ids.includes(s.id)}/>{s.name}</label>)}</div>{!specialties.length&&<small className="subtle">Carregando especialidades…</small>}</fieldset>
 <div className="formGrid"><label>Identificação<select className="select" name="document_type" value={docType} onChange={e=>setDocType(e.target.value as 'cpf'|'cnpj')}><option value="cpf" disabled={kind==='company'||kind==='agency'}>CPF</option><option value="cnpj" disabled={kind==='freelancer'}>CNPJ</option></select></label><label>{docType.toUpperCase()} privado<input className="input" name="document_number" autoComplete="off" inputMode={docType==='cpf'?'numeric':'text'} placeholder={profile?.onboarding_completed?'Preencha apenas para atualizar':''} required={!profile?.onboarding_completed} maxLength={20}/></label></div>
 {kind==='freelancer'&&<><label>Cidade<input className="input" name="city" autoComplete="address-level2"/></label><label>Disponibilidade<select className="select" name="professional_status" defaultValue={profile?.professional_status||'available'}><option value="available">Disponível</option><option value="busy">Em trabalho</option><option value="unavailable">Indisponível</option></select></label><label>Apresentação profissional<textarea className="textarea" name="bio" defaultValue={profile?.bio||''} maxLength={1000}/></label></>}
 </>;
}
function ProfileForm({profile,specialties,ids,organization,busy,submit}:{profile:Profile;specialties:Specialty[];ids:string[];organization:Organization|null;busy:boolean;submit:(p:ProfilePayload)=>Promise<void>}){
 return <form className="form" onSubmit={e=>{e.preventDefault();submit(profilePayload(e.currentTarget))}}><ProfileFields profile={profile} specialties={specialties} ids={ids} organization={organization}/><p className="subtle">Sua identificação fica privada. Nome, especialidades e apresentação compõem seu perfil profissional.</p><button className="btn" disabled={busy||!specialties.length}>{busy?'Salvando…':'Salvar meu perfil'}</button></form>
}
